# frozen_string_literal: true

namespace :mcp do
  desc "Generate MCP tool catalog from PlatformApiToolRegistry action_definitions"
  task generate_tool_catalog: :environment do
    registry = Ai::Tools::PlatformApiToolRegistry::TOOLS
    output_path = Rails.root.join("..", "docs", "platform", "MCP_TOOL_CATALOG.md")

    # Group actions by registry comment categories
    categories = {
      "Project & CI/CD" => [],
      "Agent Management" => [],
      "Team Management" => [],
      "Workflow Management" => [],
      "Pipeline Management" => [],
      "Memory Management" => [],
      "Knowledge & RAG" => [],
      "KB Article Management" => [],
      "Page Management" => [],
      "Compound Learning" => [],
      "Shared Knowledge" => [],
      "Skills" => [],
      "Knowledge Quality" => [],
      "Knowledge Graph" => []
    }

    # Map tool classes to categories based on registry comments
    class_to_category = {
      "Ai::Tools::ProjectInitTool" => "Project & CI/CD",
      "Ai::Tools::RunnerDispatchTool" => "Project & CI/CD",
      "Ai::Tools::AgentManagementTool" => "Agent Management",
      "Ai::Tools::TeamManagementTool" => "Team Management",
      "Ai::Tools::WorkflowManagementTool" => "Workflow Management",
      "Ai::Tools::PipelineManagementTool" => "Pipeline Management",
      "Ai::Tools::MemoryTool" => "Memory Management",
      "Ai::Tools::KnowledgeTool" => "Knowledge & RAG",
      "Ai::Tools::RagManagementTool" => "Knowledge & RAG",
      "Ai::Tools::ApiReferenceTool" => "Knowledge & RAG",
      "Ai::Tools::KbArticleManagementTool" => "KB Article Management",
      "Ai::Tools::PageManagementTool" => "Page Management",
      "Ai::Tools::LearningTool" => "Compound Learning",
      "Ai::Tools::SharedKnowledgeTool" => "Shared Knowledge",
      "Ai::Tools::SkillTool" => "Skills",
      "Ai::Tools::KnowledgeQualityTool" => "Knowledge Quality",
      "Ai::Tools::KnowledgeGraphTool" => "Knowledge Graph"
    }

    # Collect action definitions grouped by category
    tool_classes_seen = Set.new
    action_count = 0

    registry.each do |action_name, class_name|
      category = class_to_category[class_name] || "Uncategorized"
      categories[category] ||= []

      begin
        klass = class_name.constantize
        action_defs = klass.action_definitions

        if action_defs.key?(action_name)
          defn = action_defs[action_name]
        else
          defn = { description: klass.definition[:description], parameters: klass.definition[:parameters]&.except(:action) || {} }
        end

        permission = klass.const_defined?(:REQUIRED_PERMISSION) ? klass::REQUIRED_PERMISSION : nil

        categories[category] << {
          action: action_name,
          class_name: class_name,
          description: defn[:description],
          parameters: defn[:parameters] || {},
          permission: permission
        }

        tool_classes_seen << class_name
        action_count += 1
      rescue NameError => e
        puts "  Warning: Could not load #{class_name} for action '#{action_name}': #{e.message}"
        categories[category] << {
          action: action_name,
          class_name: class_name,
          description: "(class not found)",
          parameters: {},
          permission: nil
        }
        action_count += 1
      end
    end

    # Generate markdown
    lines = []
    lines << "# MCP Tool Catalog"
    lines << ""
    lines << "> Auto-generated by `rails mcp:generate_tool_catalog` on #{Time.current.strftime('%Y-%m-%d %H:%M UTC')}"
    lines << "> Source: `Ai::Tools::PlatformApiToolRegistry::TOOLS`"
    lines << ""
    lines << "**#{action_count} actions** across **#{tool_classes_seen.size} tool classes**"
    lines << ""
    lines << "---"
    lines << ""

    categories.each do |category, actions|
      next if actions.empty?

      lines << "## #{category}"
      lines << ""

      actions.each do |action|
        lines << "### `#{action[:action]}`"
        lines << ""
        lines << "#{action[:description]}"
        lines << ""
        lines << "- **Tool class**: `#{action[:class_name]}`"
        lines << "- **Permission**: #{action[:permission] || 'none'}"

        params = action[:parameters]
        if params.any?
          lines << ""
          lines << "| Parameter | Type | Required | Description |"
          lines << "|-----------|------|----------|-------------|"
          params.each do |param_name, spec|
            required = spec[:required] ? "Yes" : "No"
            lines << "| `#{param_name}` | #{spec[:type] || 'string'} | #{required} | #{spec[:description] || '-'} |"
          end
        else
          lines << "- **Parameters**: none"
        end

        lines << ""
      end

      lines << "---"
      lines << ""
    end

    # Write output
    FileUtils.mkdir_p(File.dirname(output_path))
    File.write(output_path, lines.join("\n"))

    puts "Generated catalog for #{action_count} actions across #{tool_classes_seen.size} tool classes"
    puts "Output: #{output_path}"
  end
end
