# frozen_string_literal: true

FactoryBot.define do
  factory :baas_invoice, class: "BaaS::Invoice" do
    association :baas_tenant, factory: :baas_tenant
    association :baas_customer, factory: :baas_customer
    baas_subscription { nil }
    sequence(:external_id) { |n| "inv_#{SecureRandom.hex(8)}_#{n}" }
    number { nil } # Generated by model callback
    status { "draft" }
    currency { "usd" }
    subtotal_cents { 10000 }
    tax_cents { 0 }
    discount_cents { 0 }
    total_cents { 10000 }
    amount_paid_cents { 0 }
    amount_due_cents { 10000 }
    due_date { 30.days.from_now }
    period_start { Time.current.beginning_of_month }
    period_end { Time.current.end_of_month }
    line_items { [{ "id" => SecureRandom.uuid, "description" => "Monthly subscription", "quantity" => 1, "unit_amount_cents" => 10000, "amount_cents" => 10000 }] }
    paid_at { nil }
    voided_at { nil }
    stripe_invoice_id { nil }
    invoice_pdf_url { nil }
    hosted_invoice_url { nil }
    metadata { {} }

    trait :open do
      status { "open" }
    end

    trait :paid do
      status { "paid" }
      paid_at { Time.current }
      amount_paid_cents { 10000 }
      amount_due_cents { 0 }
    end

    trait :void do
      status { "void" }
      voided_at { Time.current }
    end

    trait :uncollectible do
      status { "uncollectible" }
    end

    trait :overdue do
      status { "open" }
      due_date { 7.days.ago }
    end

    trait :with_tax do
      tax_cents { 1000 }
      total_cents { 11000 }
      amount_due_cents { 11000 }
    end

    trait :with_discount do
      discount_cents { 2000 }
      total_cents { 8000 }
      amount_due_cents { 8000 }
    end

    trait :with_subscription do
      association :baas_subscription, factory: :baas_subscription
    end

    trait :with_stripe do
      stripe_invoice_id { "in_#{SecureRandom.alphanumeric(24)}" }
    end
  end
end
