import { defineConfig } from 'cypress';
import cypressSplit from 'cypress-split';
import * as fs from 'fs';
import * as path from 'path';

export default defineConfig({
  e2e: {
    baseUrl: 'http://localhost:3001',
    viewportWidth: 1280,
    viewportHeight: 720,
    video: false,
    screenshotOnRunFailure: true,
    // Optimized timeouts for faster test execution
    defaultCommandTimeout: 5000,
    requestTimeout: 8000,
    responseTimeout: 8000,
    pageLoadTimeout: 15000,
    retries: {
      runMode: process.env.CI ? 2 : 0,  // No retries in dev for faster feedback
      openMode: 0,
    },
    // Parallelization settings
    // Run tests in parallel: npm run cypress:parallel:4 (splits across 4 processes)
    experimentalRunAllSpecs: true, // Enables running multiple spec files more efficiently
    setupNodeEvents(on, config) {
      // Enable cypress-split for local parallelization
      cypressSplit(on, config);

      // Load test credentials from project root (generated by rails db:seed)
      // Primary location: project root (test-credentials.json)
      const projectRoot = path.join(__dirname, '..');
      const credentialsPath = path.join(projectRoot, 'test-credentials.json');
      if (fs.existsSync(credentialsPath)) {
        try {
          const credentials = JSON.parse(fs.readFileSync(credentialsPath, 'utf-8'));
          config.env = {
            ...config.env,
            // Flat format for easy Cypress.env() access
            DEMO_EMAIL: credentials.demo?.email,
            DEMO_PASSWORD: credentials.demo?.password,
            ADMIN_EMAIL: credentials.admin?.email,
            ADMIN_PASSWORD: credentials.admin?.password,
            MANAGER_EMAIL: credentials.manager?.email,
            MANAGER_PASSWORD: credentials.manager?.password,
            BILLING_EMAIL: credentials.billing?.email,
            BILLING_PASSWORD: credentials.billing?.password,
            MEMBER_EMAIL: credentials.member?.email,
            MEMBER_PASSWORD: credentials.member?.password,
          };
          console.log('✅ Loaded test credentials from fixture file');
        } catch (err) {
          console.warn('⚠️ Failed to load test credentials:', err);
        }
      } else {
        console.warn('⚠️ Test credentials file not found at:', credentialsPath);
        console.warn('   Run "cd server && rails db:seed" to generate test-credentials.json');
      }

      return config;
    },
    env: {
      apiUrl: 'http://localhost:3000/api/v1',
      // Note: Credentials are loaded dynamically from cypress/fixtures/test-credentials.json
      // This file is generated by: cd server && rails db:seed
      // The file is gitignored and must be regenerated after cloning
    },
    supportFile: 'cypress/support/e2e.ts',
    specPattern: 'cypress/e2e/**/*.cy.{js,jsx,ts,tsx}',
  },
  component: {
    devServer: {
      framework: 'create-react-app',
      bundler: 'webpack',
    },
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    supportFile: 'cypress/support/component.ts',
    specPattern: 'cypress/component/**/*.cy.{js,jsx,ts,tsx}',
  },
});