/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        'theme-interactive-primary': 'var(--color-interactive-primary)',
        'theme-interactive-primary-hover': 'var(--color-interactive-primary-hover)',
        'theme-interactive-primary-active': 'var(--color-interactive-primary-active)',
        'theme-interactive-primary-disabled': 'var(--color-interactive-primary-disabled)',
        'theme-interactive-secondary': 'var(--color-interactive-secondary)',
        'theme-interactive-secondary-hover': 'var(--color-interactive-secondary-hover)',
        'theme-interactive-secondary-active': 'var(--color-interactive-secondary-active)',
        'theme-interactive-secondary-disabled': 'var(--color-interactive-secondary-disabled)',
        'theme-primary': 'var(--color-text-primary)',
        'theme-secondary': 'var(--color-text-secondary)',
        'theme-tertiary': 'var(--color-text-tertiary)',
        'theme-link': 'var(--color-text-link)',
        'theme-link-hover': 'var(--color-text-link-hover)',
        'theme-surface': 'var(--color-surface)',
        'theme-surface-hover': 'var(--color-surface-hover)',
        'theme-surface-selected': 'var(--color-surface-selected)',
        'theme-background-secondary': 'var(--color-background-secondary)',
        'theme-success': 'var(--color-success)',
        'theme-warning': 'var(--color-warning)',
        'theme-error': 'var(--color-error)',
        'theme-danger': 'var(--color-error)', // Alias for theme-error
        'theme-info': 'var(--color-info)',
        // Workflow node colors - all node types
        'node-trigger': 'var(--node-trigger-bg)',
        'node-ai-agent': 'var(--node-ai-agent-bg)',
        'node-data-processor': 'var(--node-data-processor-bg)',
        'node-condition': 'var(--node-condition-bg)',
        'node-loop': 'var(--node-loop-bg)',
        'node-api-call': 'var(--node-api-call-bg)',
        'node-webhook': 'var(--node-webhook-bg)',
        'node-database': 'var(--node-database-bg)',
        'node-email': 'var(--node-email-bg)',
        'node-scheduler': 'var(--node-scheduler-bg)',
        'node-file': 'var(--node-file-bg)',
        'node-transformer': 'var(--node-transformer-bg)',
        'node-validator': 'var(--node-validator-bg)',
        'node-notification': 'var(--node-notification-bg)',
        'node-delay': 'var(--node-delay-bg)',
        'node-merge': 'var(--node-merge-bg)',
        'node-split': 'var(--node-split-bg)',
        'node-end': 'var(--node-end-bg)',
        'node-start': 'var(--node-start-bg)',
        'node-prompt-template': 'var(--node-prompt-template-bg)',
        'node-human-approval': 'var(--node-human-approval-bg)',
        'node-sub-workflow': 'var(--node-sub-workflow-bg)',
        // Consolidated workflow node colors
        'node-kb-article': 'var(--node-kb-article-bg)',
        'node-kb-article-border': 'var(--node-kb-article-border)',
        'node-page': 'var(--node-page-bg)',
        'node-page-border': 'var(--node-page-border)',
        'node-mcp-operation': 'var(--node-mcp-operation-bg)',
        'node-mcp-operation-border': 'var(--node-mcp-operation-border)',
        'node-devops-trigger': 'var(--node-devops-trigger-bg)',
        'node-devops-wait-status': 'var(--node-devops-wait-status-bg)',
        'node-devops-get-logs': 'var(--node-devops-get-logs-bg)',
        // Workflow handle colors
        'handle-default': 'var(--handle-default)',
        'handle-input': 'var(--handle-input)',
        'handle-output': 'var(--handle-output)',
        'handle-true': 'var(--handle-true)',
        'handle-false': 'var(--handle-false)',
        'handle-loop-back': 'var(--handle-loop-back)',
        'handle-loop-exit': 'var(--handle-loop-exit)',
      },
      backgroundColor: {
        'theme-primary': 'var(--color-interactive-primary)',
        'theme-primary-hover': 'var(--color-interactive-primary-hover)',
        'theme-interactive-primary': 'var(--color-interactive-primary)',
        'theme-interactive-primary-hover': 'var(--color-interactive-primary-hover)',
        'theme-interactive-primary-active': 'var(--color-interactive-primary-active)',
        'theme-interactive-primary-disabled': 'var(--color-interactive-primary-disabled)',
        'theme-interactive-secondary': 'var(--color-interactive-secondary)',
        'theme-interactive-secondary-hover': 'var(--color-interactive-secondary-hover)',
        'theme-interactive-secondary-active': 'var(--color-interactive-secondary-active)',
        'theme-interactive-secondary-disabled': 'var(--color-interactive-secondary-disabled)',
        'theme-surface': 'var(--color-surface)',
        'theme-surface-hover': 'var(--color-surface-hover)',
        'theme-surface-selected': 'var(--color-surface-selected)',
        'theme-background-secondary': 'var(--color-background-secondary)',
        'theme-success': 'var(--color-success-background)',
        'theme-warning': 'var(--color-warning-background)',
        'theme-error': 'var(--color-error-background)',
        'theme-danger': 'var(--color-error-background)', // Alias for theme-error
        'theme-info': 'var(--color-info-background)',
        // Workflow node backgrounds - all node types
        'node-trigger': 'var(--node-trigger-bg)',
        'node-ai-agent': 'var(--node-ai-agent-bg)',
        'node-data-processor': 'var(--node-data-processor-bg)',
        'node-condition': 'var(--node-condition-bg)',
        'node-loop': 'var(--node-loop-bg)',
        'node-api-call': 'var(--node-api-call-bg)',
        'node-webhook': 'var(--node-webhook-bg)',
        'node-database': 'var(--node-database-bg)',
        'node-email': 'var(--node-email-bg)',
        'node-scheduler': 'var(--node-scheduler-bg)',
        'node-file': 'var(--node-file-bg)',
        'node-transformer': 'var(--node-transformer-bg)',
        'node-validator': 'var(--node-validator-bg)',
        'node-notification': 'var(--node-notification-bg)',
        'node-delay': 'var(--node-delay-bg)',
        'node-merge': 'var(--node-merge-bg)',
        'node-split': 'var(--node-split-bg)',
        'node-end': 'var(--node-end-bg)',
        'node-start': 'var(--node-start-bg)',
        'node-prompt-template': 'var(--node-prompt-template-bg)',
        'node-human-approval': 'var(--node-human-approval-bg)',
        'node-sub-workflow': 'var(--node-sub-workflow-bg)',
        // Consolidated workflow node backgrounds
        'node-kb-article': 'var(--node-kb-article-bg)',
        'node-page': 'var(--node-page-bg)',
        'node-mcp-operation': 'var(--node-mcp-operation-bg)',
        'node-devops-trigger': 'var(--node-devops-trigger-bg)',
        'node-devops-wait-status': 'var(--node-devops-wait-status-bg)',
        'node-devops-get-logs': 'var(--node-devops-get-logs-bg)',
        // Workflow handle backgrounds
        'handle-default': 'var(--handle-default)',
        'handle-input': 'var(--handle-input)',
        'handle-output': 'var(--handle-output)',
        'handle-true': 'var(--handle-true)',
        'handle-false': 'var(--handle-false)',
        'handle-loop-back': 'var(--handle-loop-back)',
        'handle-loop-exit': 'var(--handle-loop-exit)',
      },
      borderColor: {
        'theme': 'var(--color-border)',
        'theme-light': 'var(--color-border-light)',
        'theme-strong': 'var(--color-border-strong)',
        'theme-focus': 'var(--color-border-focus)',
        'theme-success': 'var(--color-success-border)',
        'theme-warning': 'var(--color-warning-border)',
        'theme-error': 'var(--color-error-border)',
        'theme-danger': 'var(--color-error-border)', // Alias for theme-error
        'theme-info': 'var(--color-info-border)',
        // Workflow node borders - all node types
        'node-trigger': 'var(--node-trigger-bg)',
        'node-ai-agent': 'var(--node-ai-agent-bg)',
        'node-data-processor': 'var(--node-data-processor-bg)',
        'node-condition': 'var(--node-condition-bg)',
        'node-loop': 'var(--node-loop-bg)',
        'node-api-call': 'var(--node-api-call-bg)',
        'node-webhook': 'var(--node-webhook-bg)',
        'node-database': 'var(--node-database-bg)',
        'node-email': 'var(--node-email-bg)',
        'node-scheduler': 'var(--node-scheduler-bg)',
        'node-file': 'var(--node-file-bg)',
        'node-transformer': 'var(--node-transformer-bg)',
        'node-validator': 'var(--node-validator-bg)',
        'node-notification': 'var(--node-notification-bg)',
        'node-delay': 'var(--node-delay-bg)',
        'node-merge': 'var(--node-merge-bg)',
        'node-split': 'var(--node-split-bg)',
        'node-end': 'var(--node-end-bg)',
        'node-start': 'var(--node-start-bg)',
        'node-prompt-template': 'var(--node-prompt-template-bg)',
        'node-human-approval': 'var(--node-human-approval-bg)',
        'node-sub-workflow': 'var(--node-sub-workflow-bg)',
        // Consolidated workflow node borders
        'node-kb-article': 'var(--node-kb-article-border)',
        'node-page': 'var(--node-page-border)',
        'node-mcp-operation': 'var(--node-mcp-operation-border)',
        'node-devops-trigger': 'var(--node-devops-trigger-border)',
        'node-devops-wait-status': 'var(--node-devops-wait-status-border)',
        'node-devops-get-logs': 'var(--node-devops-get-logs-border)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-theme-interactive-primary',
    'hover:bg-theme-interactive-primary-hover',
    'bg-theme-interactive-secondary',
    'hover:bg-theme-interactive-secondary-hover',
    'text-theme-primary',
    'text-theme-secondary',
    'text-theme-tertiary',
    'text-theme-link',
    'hover:text-theme-link-hover',
    'text-theme-success',
    'text-theme-warning',
    'text-theme-error',
    'text-theme-danger', // Alias for theme-error
    'text-theme-info',
    'text-green-800',
    'dark:text-green-100',
    'text-red-800',
    'dark:text-red-100',
    'text-yellow-800',
    'dark:text-yellow-100',
    'text-blue-800',
    'dark:text-blue-100',
    'text-green-600',
    'dark:text-green-200',
    'hover:text-green-700',
    'dark:hover:text-green-100',
    'text-red-600',
    'dark:text-red-200',
    'hover:text-red-700',
    'dark:hover:text-red-100',
    'text-yellow-600',
    'dark:text-yellow-200',
    'hover:text-yellow-700',
    'dark:hover:text-yellow-100',
    'text-blue-600',
    'dark:text-blue-200',
    'hover:text-blue-700',
    'dark:hover:text-blue-100',
    'bg-theme-surface',
    'hover:bg-theme-surface-hover',
    'bg-theme-surface-selected',
    'bg-theme-background-secondary',
    'bg-theme-success',
    'bg-theme-warning',
    'bg-theme-error',
    'bg-theme-danger', // Alias for theme-error
    'bg-theme-info',
    'bg-green-50',
    'dark:bg-green-800',
    'bg-red-50',
    'dark:bg-red-800',
    'bg-yellow-50',
    'dark:bg-yellow-800',
    'bg-blue-50',
    'dark:bg-blue-800',
    'border-theme',
    'border-theme-light',
    'border-theme-strong',
    'border-theme-focus',
    'border-theme-success',
    'border-theme-warning',
    'border-theme-error',
    'border-theme-danger', // Alias for theme-error
    'border-theme-info',
    'border-green-300',
    'dark:border-green-600',
    'border-red-300',
    'dark:border-red-600',
    'border-yellow-300',
    'dark:border-yellow-600',
    'border-blue-300',
    'dark:border-blue-600',
    'divide-theme',
    // Workflow handle classes
    'bg-handle-default',
    'bg-handle-input',
    'bg-handle-output',
    'bg-handle-true',
    'bg-handle-false',
    'bg-handle-loop-back',
    'bg-handle-loop-exit',
  ],
}