# frozen_string_literal: true

require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Use Redis when available (required for multi-process Puma), otherwise memory_store.
  if ENV["REDIS_URL"]
    config.cache_store = :redis_cache_store, { url: ENV["REDIS_URL"] }
  else
    config.cache_store = :memory_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  # ActiveStorage not loaded in API-only configuration

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # Configure ActionCable to allow local network and development origins
  config.action_cable.disable_request_forgery_protection = true
  config.action_cable.allowed_request_origins = [
    # Local development (http and ws/wss) - Frontend on 3000, Backend on 3001
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://powernode.dev:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://powernode.dev:3001",
    "ws://localhost:3000",
    "ws://127.0.0.1:3000",
    "ws://powernode.dev:3000",
    "ws://localhost:3001",
    "ws://127.0.0.1:3001",
    "ws://powernode.dev:3001",
    # Local network patterns
    /http:\/\/192\.168\.\d{1,3}\.\d{1,3}:300[0-9]/,
    /http:\/\/10\.\d{1,3}\.\d{1,3}\.\d{1,3}:300[0-9]/,
    /http:\/\/172\.(1[6-9]|2[0-9]|3[0-1])\.\d{1,3}\.\d{1,3}:300[0-9]/,
    /ws:\/\/192\.168\.\d{1,3}\.\d{1,3}:300[0-9]/,
    /ws:\/\/10\.\d{1,3}\.\d{1,3}\.\d{1,3}:300[0-9]/,
    /ws:\/\/172\.(1[6-9]|2[0-9]|3[0-1])\.\d{1,3}\.\d{1,3}:300[0-9]/,
    # Development domains - generic patterns only
    /http:\/\/[^\/]+\.local:300[0-9]/,
    /http:\/\/[^\/]+\.test:300[0-9]/,
    /ws:\/\/[^\/]+\.local:300[0-9]/,
    /ws:\/\/[^\/]+\.test:300[0-9]/,
    # Custom development domains
    /http:\/\/[^\/]+\.ipnode\.net(:\d+)?/,
    /ws:\/\/[^\/]+\.ipnode\.net(:\d+)?/
  ]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Allow external access to development server
  # Additional hosts can be added through the admin interface
  config.hosts << "localhost"
  config.hosts << "127.0.0.1"

  # Dynamic host authorization using proc - checks trusted hosts from AdminSetting
  # This allows requests from hosts configured via the admin interface
  config.hosts << ->(host) {
    # Strip port from host for matching
    host_without_port = host.to_s.split(":").first

    # Always allow localhost variants
    return true if host_without_port == "localhost" || host_without_port == "127.0.0.1"

    begin
      # Check against trusted hosts from admin settings
      return false unless defined?(AdminSetting) && ActiveRecord::Base.connection.table_exists?("admin_settings")

      proxy_config = AdminSetting.reverse_proxy_url_config
      return false unless proxy_config.is_a?(Hash) && proxy_config[:trusted_hosts].is_a?(Array)

      proxy_config[:trusted_hosts].any? do |pattern|
        next false if pattern.blank?

        pattern_host = pattern.split(":").first

        if pattern_host.start_with?("*.")
          # Wildcard match: *.example.com matches sub.example.com
          domain = pattern_host[2..] # Remove "*."
          host_without_port.end_with?(".#{domain}") || host_without_port == domain
        else
          # Exact match (case insensitive)
          host_without_port.downcase == pattern_host.downcase
        end
      end
    rescue StandardError
      false
    end
  }
end
