# frozen_string_literal: true

# Test Credentials Helper
#
# Provides access to test user credentials that are generated by the seeding process.
# Credentials are stored in the project root as test-credentials.json (gitignored).
#
# For seeded demo users (E2E/integration tests):
#   TestCredentials.demo_email      # => "demo@powernode.org"
#   TestCredentials.demo_password   # => "randomly_generated_password"
#   TestCredentials.admin           # => { email: "...", password: "..." }
#   TestCredentials.user(:billing)  # => User.find_by(email: billing_email)
#
# For factory users (unit tests):
#   TestUsers::PASSWORD             # => Standard test password
#   TestUsers::DOMAIN               # => "powernode.org"
#
# To regenerate credentials, run: rails db:seed
#
module TestCredentials
  # Primary location: project root (easily discoverable)
  PROJECT_ROOT_CREDENTIALS = Rails.root.join('..', 'test-credentials.json')
  # Detailed server credentials (includes role info)
  SERVER_CREDENTIALS_FILE = Rails.root.join('tmp', 'test_credentials.json')

  class << self
    # Load credentials from file (cached for performance)
    def credentials
      @credentials ||= load_credentials
    end

    # Clear cached credentials (useful for testing)
    def reload!
      @credentials = nil
      @users_cache = {}
      credentials
    end

    # Demo user credentials
    def demo_email
      credentials.dig('users', 'demo', 'email') || 'demo@powernode.org'
    end

    def demo_password
      credentials.dig('users', 'demo', 'password') || raise_missing_credentials('demo')
    end

    def demo
      { email: demo_email, password: demo_password }
    end

    # Admin user credentials
    def admin_email
      credentials.dig('users', 'admin', 'email') || 'admin@powernode.org'
    end

    def admin_password
      credentials.dig('users', 'admin', 'password') || raise_missing_credentials('admin')
    end

    def admin
      { email: admin_email, password: admin_password }
    end

    # Billing manager credentials
    def billing_email
      credentials.dig('users', 'billing', 'email') || 'billing@powernode.org'
    end

    def billing_password
      credentials.dig('users', 'billing', 'password') || raise_missing_credentials('billing')
    end

    def billing
      { email: billing_email, password: billing_password }
    end

    # Member credentials
    def member_email
      credentials.dig('users', 'member', 'email') || 'member@powernode.org'
    end

    def member_password
      credentials.dig('users', 'member', 'password') || raise_missing_credentials('member')
    end

    def member
      { email: member_email, password: member_password }
    end

    # Manager credentials
    def manager_email
      credentials.dig('users', 'manager', 'email') || 'manager@powernode.org'
    end

    def manager_password
      credentials.dig('users', 'manager', 'password') || raise_missing_credentials('manager')
    end

    def manager
      { email: manager_email, password: manager_password }
    end

    # Get credentials by role name
    def for_role(role_name)
      role_name = role_name.to_s.downcase
      case role_name
      when 'demo'
        demo
      when 'admin', 'super_admin'
        admin
      when 'manager'
        manager
      when 'billing', 'billing_manager'
        billing
      when 'member'
        member
      else
        raise ArgumentError, "Unknown role: #{role_name}. Available: demo, admin, manager, billing, member"
      end
    end

    # Find or create the actual User record for a test user
    # Useful when you need the user model, not just credentials
    def user(role_name = :demo)
      @users_cache ||= {}
      @users_cache[role_name.to_sym] ||= begin
        creds = for_role(role_name)
        User.find_by!(email: creds[:email])
      rescue ActiveRecord::RecordNotFound
        raise "Test user #{role_name} not found. Run 'rails db:seed' to create test users."
      end
    end

    # Create authenticated request headers for a test user
    def auth_headers_for(role_name = :demo)
      test_user = user(role_name)
      token = Security::JwtService.encode(
        sub: test_user.id,
        account_id: test_user.account_id,
        email: test_user.email,
        type: 'access',
        permissions: test_user.permission_names,
        version: Security::JwtService::CURRENT_TOKEN_VERSION
      )
      {
        'Authorization' => "Bearer #{token}",
        'Content-Type' => 'application/json'
      }
    end

    # Check if credentials file exists
    def available?
      File.exist?(PROJECT_ROOT_CREDENTIALS) || File.exist?(SERVER_CREDENTIALS_FILE)
    end

    private

    def load_credentials
      # Try server credentials first (more detailed)
      if File.exist?(SERVER_CREDENTIALS_FILE)
        return JSON.parse(File.read(SERVER_CREDENTIALS_FILE))
      end

      # Fall back to project root credentials (hash format)
      if File.exist?(PROJECT_ROOT_CREDENTIALS)
        frontend_creds = JSON.parse(File.read(PROJECT_ROOT_CREDENTIALS))
        return {
          'users' => {
            'demo' => frontend_creds['demo'],
            'admin' => frontend_creds['admin'],
            'billing' => frontend_creds['billing'],
            'member' => frontend_creds['member']
          }
        }
      end

      warn_missing_credentials_file
      {}
    rescue JSON::ParserError => e
      Rails.logger.error "Failed to parse test credentials: #{e.message}"
      {}
    end

    def raise_missing_credentials(role)
      raise <<~ERROR
        Test credentials for '#{role}' not found!

        The test credentials file (test-credentials.json) is missing or incomplete.

        To generate test credentials, run:
          cd server && rails db:seed

        This will create test users with randomly generated passwords and save
        the credentials to the project root as test-credentials.json.

        Note: This file is gitignored and must be regenerated after cloning.
      ERROR
    end

    def warn_missing_credentials_file
      warning = <<~WARN
        ⚠️  Test credentials file not found!
           Looked in: #{PROJECT_ROOT_CREDENTIALS}
                      #{SERVER_CREDENTIALS_FILE}

        Run 'rails db:seed' to generate test users and credentials.
        Tests requiring authentication may fail without this file.
      WARN
      Rails.logger.warn warning
      warn warning if ENV['RAILS_ENV'] == 'test'
    end
  end
end

# Make TestCredentials available globally in tests
RSpec.configure do |config|
  config.before(:suite) do
    unless TestCredentials.available?
      Rails.logger.warn "\n⚠️  Test credentials not found. Run 'rails db:seed' to generate.\n"
    end
  end
end
