import { test as setup, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const authFile = 'e2e/.auth/user.json';

/**
 * Global setup for Playwright tests
 *
 * Authenticates a test user and stores the session for reuse across all tests.
 * Credentials are loaded from test-credentials.json (generated by rails db:seed).
 */
setup('authenticate', async ({ page }) => {
  // Ensure auth directory exists
  const authDir = path.dirname(authFile);
  if (!fs.existsSync(authDir)) {
    fs.mkdirSync(authDir, { recursive: true });
  }

  // Load test credentials
  const credentials = loadTestCredentials();

  // Navigate to login page
  await page.goto('/login');

  // Wait for login form to be ready
  await page.waitForSelector('input[type="email"], input[name="email"]', { timeout: 30000 });

  // Fill in credentials
  await page.fill('input[type="email"], input[name="email"]', credentials.email);
  await page.fill('input[type="password"], input[name="password"]', credentials.password);

  // Submit login form
  await page.click('button[type="submit"]');

  // Wait for successful login - should redirect to dashboard or app
  await page.waitForURL(/\/(app|dashboard)/, { timeout: 30000 });

  // Verify we're logged in by checking for common authenticated UI elements
  await expect(page.locator('body')).toBeVisible();

  // Save authentication state
  await page.context().storageState({ path: authFile });
});

/**
 * Load test credentials from test-credentials.json
 * Falls back to environment variables or defaults
 */
function loadTestCredentials(): { email: string; password: string } {
  // First check environment variables (highest priority)
  if (process.env.TEST_USER_EMAIL && process.env.TEST_USER_PASSWORD) {
    return {
      email: process.env.TEST_USER_EMAIL,
      password: process.env.TEST_USER_PASSWORD,
    };
  }

  // Try to load from test-credentials.json (generated by rails db:seed)
  const credentialsPath = path.join(process.cwd(), 'test-credentials.json');

  if (fs.existsSync(credentialsPath)) {
    try {
      const content = fs.readFileSync(credentialsPath, 'utf-8');
      const parsed = JSON.parse(content);

      // Look for admin user with AI permissions
      if (parsed.admin?.email && parsed.admin?.password) {
        return {
          email: parsed.admin.email,
          password: parsed.admin.password,
        };
      }

      // Fallback to demo user
      if (parsed.demo?.email && parsed.demo?.password) {
        return {
          email: parsed.demo.email,
          password: parsed.demo.password,
        };
      }
    } catch {
      // Failed to parse credentials file, fall through to defaults
    }
  }

  // Default credentials for development (these may not work)
  return {
    email: 'admin@powernode.org',
    password: 'password123',
  };
}
