# frozen_string_literal: true

require 'rails_helper'

RSpec.describe AiWorkflowNodeExecution, type: :model do
  subject(:execution) { build(:ai_workflow_node_execution) }

  describe 'associations' do
    it { is_expected.to belong_to(:ai_workflow_run) }
    it { is_expected.to belong_to(:ai_workflow_node) }
    it { is_expected.to belong_to(:ai_agent_execution).optional }
    it { is_expected.to have_many(:ai_workflow_run_logs).dependent(:destroy) }
  end

  describe 'validations' do
    # execution_id is auto-generated by before_validation callback, so we test that instead
    it 'auto-generates execution_id if not provided' do
      exec = build(:ai_workflow_node_execution, execution_id: nil)
      exec.valid?
      expect(exec.execution_id).to be_present
    end

    it { is_expected.to validate_presence_of(:node_id) }
    it { is_expected.to validate_presence_of(:node_type) }
    it { is_expected.to validate_presence_of(:status) }
    it { is_expected.to validate_numericality_of(:retry_count).is_greater_than_or_equal_to(0) }
    it { is_expected.to validate_numericality_of(:max_retries).is_greater_than_or_equal_to(0) }
    it { is_expected.to validate_numericality_of(:cost).is_greater_than_or_equal_to(0) }

    it 'validates inclusion of status' do
      valid_statuses = %w[pending running completed failed cancelled skipped waiting_approval]

      valid_statuses.each do |status|
        exec = build(:ai_workflow_node_execution, status: status)
        expect(exec).to be_valid, "Expected #{status} to be valid"
      end
    end

    it 'rejects invalid status' do
      exec = build(:ai_workflow_node_execution, status: 'invalid')
      expect(exec).not_to be_valid
      expect(exec.errors[:status]).to be_present
    end

    context 'retry limit validation' do
      it 'validates retry_count cannot exceed max_retries' do
        exec = build(:ai_workflow_node_execution, retry_count: 5, max_retries: 3)
        expect(exec).not_to be_valid
        expect(exec.errors[:retry_count]).to include('cannot exceed max_retries')
      end

      it 'allows retry_count equal to max_retries' do
        exec = build(:ai_workflow_node_execution, retry_count: 3, max_retries: 3)
        expect(exec).to be_valid
      end
    end
  end

  describe 'scopes' do
    describe '.by_node_type' do
      let!(:ai_agent_exec) { create(:ai_workflow_node_execution, node_type: 'ai_agent') }
      let!(:api_call_exec) { create(:ai_workflow_node_execution, node_type: 'api_call') }

      it 'filters executions by node type' do
        expect(described_class.by_node_type('ai_agent')).to include(ai_agent_exec)
        expect(described_class.by_node_type('ai_agent')).not_to include(api_call_exec)
      end
    end

    describe '.active' do
      let!(:pending_exec) { create(:ai_workflow_node_execution, status: 'pending') }
      let!(:running_exec) { create(:ai_workflow_node_execution, status: 'running') }
      let!(:completed_exec) { create(:ai_workflow_node_execution, status: 'completed') }

      it 'returns pending and running executions' do
        expect(described_class.active).to include(pending_exec)
        expect(described_class.active).to include(running_exec)
        expect(described_class.active).not_to include(completed_exec)
      end
    end

    describe '.completed' do
      let!(:completed_exec) { create(:ai_workflow_node_execution, status: 'completed') }
      let!(:pending_exec) { create(:ai_workflow_node_execution, status: 'pending') }

      it 'returns completed executions' do
        expect(described_class.completed).to include(completed_exec)
        expect(described_class.completed).not_to include(pending_exec)
      end
    end

    describe '.failed' do
      let!(:failed_exec) { create(:ai_workflow_node_execution, status: 'failed') }
      let!(:completed_exec) { create(:ai_workflow_node_execution, status: 'completed') }

      it 'returns failed executions' do
        expect(described_class.failed).to include(failed_exec)
        expect(described_class.failed).not_to include(completed_exec)
      end
    end

    describe '.finished' do
      let!(:completed_exec) { create(:ai_workflow_node_execution, status: 'completed') }
      let!(:failed_exec) { create(:ai_workflow_node_execution, status: 'failed') }
      let!(:running_exec) { create(:ai_workflow_node_execution, status: 'running') }

      it 'returns completed and failed executions' do
        expect(described_class.finished).to include(completed_exec)
        expect(described_class.finished).to include(failed_exec)
        expect(described_class.finished).not_to include(running_exec)
      end
    end

    describe '.with_cost' do
      let!(:with_cost) { create(:ai_workflow_node_execution, cost: 0.5) }
      let!(:no_cost) { create(:ai_workflow_node_execution, cost: 0) }

      it 'returns executions with non-zero cost' do
        expect(described_class.with_cost).to include(with_cost)
        expect(described_class.with_cost).not_to include(no_cost)
      end
    end
  end

  describe 'callbacks' do
    describe 'before_create' do
      it 'generates execution_id if not present' do
        exec = build(:ai_workflow_node_execution, execution_id: nil)
        exec.valid?
        expect(exec.execution_id).to be_present
      end

      it 'preserves provided execution_id' do
        custom_id = SecureRandom.uuid
        exec = build(:ai_workflow_node_execution, execution_id: custom_id)
        exec.valid?
        expect(exec.execution_id).to eq(custom_id)
      end
    end
  end

  describe 'status check methods' do
    describe '#pending?' do
      it 'returns true for pending status' do
        exec = build(:ai_workflow_node_execution, status: 'pending')
        expect(exec.pending?).to be true
      end
    end

    describe '#running?' do
      it 'returns true for running status' do
        exec = build(:ai_workflow_node_execution, status: 'running')
        expect(exec.running?).to be true
      end
    end

    describe '#completed?' do
      it 'returns true for completed status' do
        exec = build(:ai_workflow_node_execution, status: 'completed')
        expect(exec.completed?).to be true
      end
    end

    describe '#failed?' do
      it 'returns true for failed status' do
        exec = build(:ai_workflow_node_execution, status: 'failed')
        expect(exec.failed?).to be true
      end

      it 'returns false for other statuses' do
        exec = build(:ai_workflow_node_execution, status: 'completed')
        expect(exec.failed?).to be false
      end
    end

    describe '#cancelled?' do
      it 'returns true for cancelled status' do
        exec = build(:ai_workflow_node_execution, status: 'cancelled')
        expect(exec.cancelled?).to be true
      end
    end

    describe '#skipped?' do
      it 'returns true for skipped status' do
        exec = build(:ai_workflow_node_execution, status: 'skipped')
        expect(exec.skipped?).to be true
      end
    end

    describe '#waiting_for_approval?' do
      it 'returns true for waiting_approval status' do
        exec = build(:ai_workflow_node_execution, status: 'waiting_approval')
        expect(exec.waiting_for_approval?).to be true
      end
    end

    describe '#active?' do
      it 'returns true for pending status' do
        exec = build(:ai_workflow_node_execution, status: 'pending')
        expect(exec.active?).to be true
      end

      it 'returns true for running status' do
        exec = build(:ai_workflow_node_execution, status: 'running')
        expect(exec.active?).to be true
      end

      it 'returns true for waiting_approval status' do
        exec = build(:ai_workflow_node_execution, status: 'waiting_approval')
        expect(exec.active?).to be true
      end

      it 'returns false for completed status' do
        exec = build(:ai_workflow_node_execution, status: 'completed')
        expect(exec.active?).to be false
      end

      it 'returns false for failed status' do
        exec = build(:ai_workflow_node_execution, status: 'failed')
        expect(exec.active?).to be false
      end

      it 'returns false for cancelled status' do
        exec = build(:ai_workflow_node_execution, status: 'cancelled')
        expect(exec.active?).to be false
      end

      it 'returns false for skipped status' do
        exec = build(:ai_workflow_node_execution, status: 'skipped')
        expect(exec.active?).to be false
      end
    end

    describe '#finished?' do
      it 'returns true for completed status' do
        exec = build(:ai_workflow_node_execution, status: 'completed')
        expect(exec.finished?).to be true
      end

      it 'returns true for failed status' do
        exec = build(:ai_workflow_node_execution, status: 'failed')
        expect(exec.finished?).to be true
      end

      it 'returns true for cancelled status' do
        exec = build(:ai_workflow_node_execution, status: 'cancelled')
        expect(exec.finished?).to be true
      end

      it 'returns true for skipped status' do
        exec = build(:ai_workflow_node_execution, status: 'skipped')
        expect(exec.finished?).to be true
      end
    end

    describe '#successful?' do
      it 'returns true for completed status' do
        exec = build(:ai_workflow_node_execution, status: 'completed')
        expect(exec.successful?).to be true
      end

      it 'returns true for skipped status' do
        exec = build(:ai_workflow_node_execution, status: 'skipped')
        expect(exec.successful?).to be true
      end
    end
  end

  describe 'instance methods' do
    describe '#execution_duration' do
      it 'returns nil when not started' do
        exec = create(:ai_workflow_node_execution, started_at: nil)
        expect(exec.execution_duration).to be_nil
      end

      it 'returns duration from start to completion' do
        started = 5.minutes.ago
        completed = 2.minutes.ago
        exec = create(:ai_workflow_node_execution, started_at: started, completed_at: completed)
        expect(exec.execution_duration).to be_within(1).of(180)
      end

      it 'returns duration from start to now for running executions' do
        exec = create(:ai_workflow_node_execution, status: 'running', started_at: 2.minutes.ago)
        expect(exec.execution_duration).to be_within(5).of(120)
      end
    end

    describe '#can_retry?' do
      it 'returns true for failed executions within retry limit' do
        exec = create(:ai_workflow_node_execution, status: 'failed', retry_count: 1, max_retries: 3)
        expect(exec.can_retry?).to be true
      end

      it 'returns false for executions that exceeded retry limit' do
        exec = create(:ai_workflow_node_execution, status: 'failed', retry_count: 3, max_retries: 3)
        expect(exec.can_retry?).to be false
      end

      it 'returns false for non-failed executions' do
        exec = create(:ai_workflow_node_execution, status: 'completed', retry_count: 0, max_retries: 3)
        expect(exec.can_retry?).to be false
      end
    end

    describe '#timed_out?' do
      it 'returns false for non-running executions' do
        exec = create(:ai_workflow_node_execution, status: 'completed')
        expect(exec.timed_out?).to be false
      end

      it 'returns false when started_at is nil' do
        exec = create(:ai_workflow_node_execution, status: 'running', started_at: nil)
        expect(exec.timed_out?).to be false
      end
    end

    describe '#execution_summary' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'completed', cost: 0.5) }

      it 'returns comprehensive execution summary' do
        summary = exec.execution_summary

        expect(summary).to include(
          :execution_id,
          :node_id,
          :node_type,
          :node_name,
          :status,
          :cost,
          :retry_count,
          :max_retries,
          :timestamps
        )

        expect(summary[:status]).to eq('completed')
        expect(summary[:cost]).to eq(0.5)
      end
    end

    describe '#get_input' do
      let(:exec) { build(:ai_workflow_node_execution, input_data: { 'key1' => 'value1' }) }

      it 'retrieves input data by key' do
        expect(exec.get_input('key1')).to eq('value1')
      end

      it 'returns nil for missing key' do
        expect(exec.get_input('missing')).to be_nil
      end
    end

    describe '#node_configuration' do
      it 'returns configuration from node' do
        exec = create(:ai_workflow_node_execution)
        config = exec.node_configuration
        expect(config).to be_a(Hash)
      end
    end
  end

  describe 'execution control methods' do
    describe '#start_execution!' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'pending') }

      it 'transitions from pending to running' do
        exec.start_execution!
        expect(exec.reload.status).to eq('running')
        expect(exec.started_at).to be_present
      end

      it 'returns false if not pending' do
        exec.update!(status: 'running')
        expect(exec.start_execution!).to be_falsy
      end
    end

    describe '#complete_execution!' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'running', started_at: 1.minute.ago) }

      it 'transitions from running to completed' do
        exec.complete_execution!({ result: 'success' }, 0.05)
        expect(exec.reload.status).to eq('completed')
        expect(exec.completed_at).to be_present
        expect(exec.output_data['result']).to eq('success')
      end

      it 'returns false if not running' do
        exec.update!(status: 'pending')
        expect(exec.complete_execution!).to be false
      end
    end

    describe '#fail_execution!' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'running', started_at: 1.minute.ago) }

      it 'transitions to failed with error details' do
        exec.fail_execution!('Something went wrong', { code: 'ERR001' })
        exec.reload
        expect(exec.status).to eq('failed')
        expect(exec.error_details['error_message']).to eq('Something went wrong')
        expect(exec.error_details['code']).to eq('ERR001')
      end
    end

    describe '#cancel_execution!' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'running', started_at: 1.minute.ago) }

      it 'transitions to cancelled' do
        exec.cancel_execution!('User requested')
        expect(exec.reload.status).to eq('cancelled')
        expect(exec.error_details['cancellation_reason']).to eq('User requested')
      end

      it 'returns false if already finished' do
        exec.update!(status: 'completed')
        expect(exec.cancel_execution!).to be false
      end
    end

    describe '#skip_execution!' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'pending') }

      it 'transitions from pending to skipped' do
        exec.skip_execution!('Condition not met')
        expect(exec.reload.status).to eq('skipped')
        expect(exec.metadata['skip_reason']).to eq('Condition not met')
      end

      it 'returns false if not pending' do
        exec.update!(status: 'running')
        expect(exec.skip_execution!).to be false
      end
    end
  end

  describe 'retry management' do
    describe '#retry_execution!' do
      let(:exec) { create(:ai_workflow_node_execution, status: 'failed', retry_count: 1, max_retries: 3) }

      it 'increments retry count and resets status' do
        exec.retry_execution!
        exec.reload
        expect(exec.retry_count).to eq(2)
        expect(exec.status).to eq('pending')
      end

      it 'returns false when retry limit exceeded' do
        exec.update!(retry_count: 3)
        expect(exec.retry_execution!).to be false
      end
    end

    describe '#exhaust_retries!' do
      let(:exec) { create(:ai_workflow_node_execution, retry_count: 1, max_retries: 5) }

      it 'sets retry_count to max_retries' do
        exec.exhaust_retries!
        expect(exec.reload.retry_count).to eq(5)
      end
    end
  end

  describe 'edge cases' do
    describe 'large data handling' do
      it 'handles large input data' do
        large_input = { 'data' => 'x' * 100_000 }
        exec = build(:ai_workflow_node_execution, input_data: large_input)
        expect(exec).to be_valid
      end

      it 'handles large output data' do
        large_output = { 'data' => 'x' * 100_000 }
        exec = build(:ai_workflow_node_execution, output_data: large_output)
        expect(exec).to be_valid
      end
    end

    describe 'unicode support' do
      it 'handles unicode in input data' do
        exec = build(:ai_workflow_node_execution, input_data: { 'message' => '你好世界 🌍' })
        expect(exec).to be_valid
      end

      it 'handles unicode in error messages' do
        exec = create(:ai_workflow_node_execution, status: 'running')
        exec.fail_execution!('错误信息 🔴')
        expect(exec.reload.error_details['error_message']).to eq('错误信息 🔴')
      end
    end
  end
end
