# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Billing::Invoice, type: :model do
  let(:invoice) { build(:invoice) }

  describe "associations" do
    it { should belong_to(:subscription) }
    it { should belong_to(:account) }
    it { should have_many(:invoice_line_items).dependent(:destroy) }
    it { should have_many(:payments).dependent(:destroy) }
  end

  describe "validations" do
    subject { build(:invoice) }

    # invoice_number is auto-generated by before_validation callback, so presence test not needed
    it { should validate_uniqueness_of(:invoice_number) }
    it { should validate_presence_of(:subtotal_cents) }
    it { should validate_numericality_of(:subtotal_cents).is_greater_than_or_equal_to(0) }
    it { should validate_presence_of(:tax_cents) }
    it { should validate_numericality_of(:tax_cents).is_greater_than_or_equal_to(0) }
    it { should validate_presence_of(:total_cents) }
    it { should validate_numericality_of(:total_cents).is_greater_than_or_equal_to(0) }
    # currency is auto-set by after_initialize callback, so presence test not needed
    describe "currency validation" do
      it "validates that currency is in the allowed list" do
        invoice = build(:invoice, currency: "USD")
        expect(invoice).to be_valid

        invoice.currency = "EUR"
        expect(invoice).to be_valid

        invoice.currency = "GBP"
        expect(invoice).to be_valid

        invoice.currency = "JPY"
        expect(invoice).not_to be_valid
        expect(invoice.errors[:currency]).to include("is not included in the list")
      end
    end
    it { should validate_presence_of(:status) }
    it { should validate_inclusion_of(:status).in_array(%w[draft open paid void uncollectible]) }
    it { should validate_presence_of(:tax_rate) }
    it { should validate_numericality_of(:tax_rate).is_greater_than_or_equal_to(0).is_less_than(1) }
  end

  describe "scopes" do
    let!(:draft_invoice) { create(:invoice, status: "draft") }
    let!(:open_invoice) { create(:invoice, status: "open") }
    let!(:paid_invoice) { create(:invoice, status: "paid") }
    let!(:overdue_invoice) { create(:invoice, status: "open", due_at: 1.day.ago) }
    let!(:due_soon_invoice) { create(:invoice, status: "open", due_at: 3.days.from_now) }

    it "returns draft invoices" do
      expect(Billing::Invoice.draft).to include(draft_invoice)
      expect(Billing::Invoice.draft).not_to include(open_invoice, paid_invoice)
    end

    it "returns open invoices" do
      expect(Billing::Invoice.open).to include(open_invoice, overdue_invoice, due_soon_invoice)
      expect(Billing::Invoice.open).not_to include(draft_invoice, paid_invoice)
    end

    it "returns paid invoices" do
      expect(Billing::Invoice.paid).to include(paid_invoice)
      expect(Billing::Invoice.paid).not_to include(draft_invoice, open_invoice)
    end

    it "returns overdue invoices" do
      expect(Billing::Invoice.overdue).to include(overdue_invoice)
      expect(Billing::Invoice.overdue).not_to include(draft_invoice, paid_invoice, due_soon_invoice)
    end

    it "returns invoices due soon" do
      expect(Billing::Invoice.due_soon).to include(due_soon_invoice)
      expect(Billing::Invoice.due_soon).not_to include(draft_invoice, paid_invoice, overdue_invoice)
    end
  end

  describe "callbacks" do
    describe "#generate_invoice_number" do
      it "generates unique invoice number on create" do
        invoice = build(:invoice, invoice_number: nil)
        invoice.save!

        expect(invoice.invoice_number).to be_present
        expect(invoice.invoice_number).to match(/\AINV-\d{6}-\d{4}\z/)
      end

      it "doesn't override existing invoice number" do
        existing_number = "CUSTOM-001"
        invoice = build(:invoice, invoice_number: existing_number)
        invoice.save!

        expect(invoice.invoice_number).to eq(existing_number)
      end

      it "generates sequential invoice numbers" do
        first_invoice = create(:invoice)
        second_invoice = create(:invoice)

        first_number = first_invoice.invoice_number.split("-").last.to_i
        second_number = second_invoice.invoice_number.split("-").last.to_i

        expect(second_number).to eq(first_number + 1)
      end
    end

    describe "#calculate_totals" do
      it "calculates totals based on line items" do
        # Create invoice without any initial values for totals
        invoice = create(:invoice, tax_rate: 0.1, subtotal_cents: 0, tax_cents: 0, total_cents: 0)

        # Clear any existing line items that might be created by factory
        invoice.invoice_line_items.destroy_all

        # Create line items with unit prices that will result in desired total_cents
        # Line item callback calculates: total_cents = quantity * unit_amount_cents
        create(:invoice_line_item, invoice: invoice, quantity: 1, unit_amount_cents: 1000)
        create(:invoice_line_item, invoice: invoice, quantity: 1, unit_amount_cents: 500)

        # Reload and trigger calculation
        invoice.reload
        invoice.save!

        expect(invoice.subtotal_cents).to eq(1500)
        expect(invoice.tax_cents).to eq(150)
        expect(invoice.total_cents).to eq(1650)
      end

      it "handles zero tax rate" do
        # Create invoice with zero values and clear any factory line items
        invoice = create(:invoice, tax_rate: 0.0, subtotal_cents: 0, tax_cents: 0, total_cents: 0)
        invoice.invoice_line_items.destroy_all

        # Create line item with unit price that will result in desired total_cents
        create(:invoice_line_item, invoice: invoice, quantity: 1, unit_amount_cents: 1000)

        # Reload and trigger calculation
        invoice.reload
        invoice.save!

        expect(invoice.subtotal_cents).to eq(1000)
        expect(invoice.tax_cents).to eq(0)
        expect(invoice.total_cents).to eq(1000)
      end
    end

    describe "#set_defaults" do
      it "initializes default values" do
        subscription = create(:subscription)
        invoice = Billing::Invoice.new(subscription: subscription)

        expect(invoice.metadata).to eq({})
        # billing_address column doesn't exist - removed from model
        expect(invoice.currency).to eq(subscription.plan.currency)
      end

      it "defaults to USD when no subscription plan currency" do
        subscription = build(:subscription)
        allow(subscription).to receive_message_chain(:plan, :currency).and_return(nil)
        invoice = Billing::Invoice.new(subscription: subscription)

        expect(invoice.currency).to eq("USD")
      end
    end
  end

  describe "state machine" do
    describe "initial state" do
      it "starts in draft state" do
        invoice = build(:invoice)
        expect(invoice.status).to eq("draft")
        expect(invoice).to be_draft
      end
    end

    describe "#finalize" do
      it "transitions from draft to open" do
        invoice = create(:invoice, status: "draft")

        expect { invoice.finalize! }.to change { invoice.status }.from("draft").to("open")
      end

      it "sets due_at if not present" do
        invoice = create(:invoice, status: "draft", due_at: nil)

        start_time = Time.current
        invoice.finalize!
        expect(invoice.due_at).to be_within(2.seconds).of(start_time + 30.days)
      end

      it "doesn't override existing due_at" do
        due_at = 15.days.from_now
        invoice = create(:invoice, status: "draft", due_at: due_at)

        invoice.finalize!
        expect(invoice.due_at).to be_within(1.second).of(due_at)
      end
    end

    describe "#mark_paid" do
      it "transitions from open to paid" do
        invoice = create(:invoice, status: "open")

        expect { invoice.mark_paid! }.to change { invoice.status }.from("open").to("paid")
      end

      it "transitions from uncollectible to paid" do
        invoice = create(:invoice, status: "uncollectible")

        expect { invoice.mark_paid! }.to change { invoice.status }.from("uncollectible").to("paid")
      end

      it "sets paid_at timestamp" do
        invoice = create(:invoice, status: "open")

        start_time = Time.current
        invoice.mark_paid!
        expect(invoice.paid_at).to be_within(2.seconds).of(start_time)
      end
    end

    describe "#void" do
      it "transitions from draft to void" do
        invoice = create(:invoice, status: "draft")

        expect { invoice.void! }.to change { invoice.status }.from("draft").to("void")
      end

      it "transitions from open to void" do
        invoice = create(:invoice, status: "open")

        expect { invoice.void! }.to change { invoice.status }.from("open").to("void")
      end
    end

    describe "#mark_uncollectible" do
      it "transitions from open to uncollectible" do
        invoice = create(:invoice, status: "open")

        expect { invoice.mark_uncollectible! }.to change { invoice.status }.from("open").to("uncollectible")
      end
    end
  end

  describe "instance methods" do
    describe "#paid?" do
      it "returns true when status is paid" do
        invoice = build(:invoice, status: "paid")
        expect(invoice.paid?).to be true
      end

      it "returns false when status is not paid" do
        invoice = build(:invoice, status: "open")
        expect(invoice.paid?).to be false
      end
    end

    describe "#overdue?" do
      it "returns true when open and past due date" do
        invoice = build(:invoice, status: "open", due_at: 1.day.ago)
        expect(invoice.overdue?).to be true
      end

      it "returns false when not open" do
        invoice = build(:invoice, status: "paid", due_at: 1.day.ago)
        expect(invoice.overdue?).to be false
      end

      it "returns false when no due date" do
        invoice = build(:invoice, status: "open", due_at: nil)
        expect(invoice.overdue?).to be false
      end

      it "returns false when due date is in future" do
        invoice = build(:invoice, status: "open", due_at: 1.day.from_now)
        expect(invoice.overdue?).to be false
      end
    end

    describe "#days_overdue" do
      it "returns number of days overdue" do
        invoice = build(:invoice, status: "open", due_at: 5.days.ago.to_date)
        expect(invoice.days_overdue).to eq(5)
      end

      it "returns 0 when not overdue" do
        invoice = build(:invoice, status: "open", due_at: 1.day.from_now)
        expect(invoice.days_overdue).to eq(0)
      end

      it "returns 0 when not open" do
        invoice = build(:invoice, status: "paid", due_at: 5.days.ago)
        expect(invoice.days_overdue).to eq(0)
      end
    end

    describe "#days_until_due" do
      it "returns number of days until due" do
        invoice = build(:invoice, status: "open", due_at: 5.days.from_now.to_date)
        expect(invoice.days_until_due).to eq(5)
      end

      it "returns 0 when no due date" do
        invoice = build(:invoice, status: "open", due_at: nil)
        expect(invoice.days_until_due).to eq(0)
      end

      it "returns 0 when not open" do
        invoice = build(:invoice, status: "paid", due_at: 5.days.from_now)
        expect(invoice.days_until_due).to eq(0)
      end
    end

    describe "money methods" do
      let(:invoice) do
        invoice = create(:invoice, tax_rate: 0.1, currency: "USD")
        # Create line items that will result in the expected totals
        create(:invoice_line_item, invoice: invoice, unit_amount_cents: 1000, quantity: 2) # 2000 cents
        invoice.reload # Reload to recalculate totals
        invoice.save! # Trigger calculate_totals callback
        invoice
      end

      describe "#subtotal" do
        it "returns Money object for subtotal" do
          expect(invoice.subtotal).to be_a(Money)
          expect(invoice.subtotal.cents).to eq(2000)
          expect(invoice.subtotal.currency.to_s).to eq("USD")
        end
      end

      describe "#tax_amount" do
        it "returns Money object for tax" do
          expect(invoice.tax_amount).to be_a(Money)
          expect(invoice.tax_amount.cents).to eq(200)
          expect(invoice.tax_amount.currency.to_s).to eq("USD")
        end
      end

      describe "#total" do
        it "returns Money object for total" do
          expect(invoice.total).to be_a(Money)
          expect(invoice.total.cents).to eq(2200)
          expect(invoice.total.currency.to_s).to eq("USD")
        end
      end
    end

    describe "#payment_provider" do
      it "returns 'stripe' when stripe_invoice_id is present" do
        invoice = build(:invoice, stripe_invoice_id: "in_123")
        expect(invoice.payment_provider).to eq("stripe")
      end

      it "returns 'paypal' when paypal_invoice_id is present" do
        invoice = build(:invoice, paypal_invoice_id: "INV2-123")
        expect(invoice.payment_provider).to eq("paypal")
      end

      it "returns 'none' when no provider IDs are present" do
        invoice = build(:invoice)
        expect(invoice.payment_provider).to eq("none")
      end

      it "prefers stripe over paypal when both are present" do
        invoice = build(:invoice, stripe_invoice_id: "in_123", paypal_invoice_id: "INV2-123")
        expect(invoice.payment_provider).to eq("stripe")
      end
    end

    describe "#add_line_item" do
      it "builds a new line item with correct attributes" do
        invoice = create(:invoice)
        line_item = invoice.add_line_item(
          description: "Test Item",
          quantity: 2,
          unit_amount_cents: 1000
        )

        expect(line_item).to be_a(Billing::InvoiceLineItem)
        expect(line_item.description).to eq("Test Item")
        expect(line_item.quantity).to eq(2)
        expect(line_item.unit_amount_cents).to eq(1000)
        expect(line_item.total_cents).to eq(2000)
        expect(line_item.invoice).to eq(invoice)
      end

      it "accepts additional options" do
        invoice = create(:invoice)
        line_item = invoice.add_line_item(
          description: "Test Item",
          quantity: 1,
          unit_amount_cents: 1000,
          line_type: "subscription",
          period_start: Date.current,
          period_end: 1.month.from_now
        )

        expect(line_item.line_type).to eq("subscription")
        expect(line_item.period_start).to eq(Date.current)
        expect(line_item.period_end.to_date).to eq(1.month.from_now.to_date)
      end
    end

    describe "#add_subscription_line_item" do
      let(:plan) { create(:plan, name: "Pro Plan", billing_cycle: "monthly", price_cents: 2999) }
      let(:subscription) { create(:subscription, plan: plan) }
      let(:invoice) { create(:invoice, subscription: subscription) }

      it "adds subscription line item with plan details" do
        line_item = invoice.add_subscription_line_item(plan)

        expect(line_item.description).to eq("Pro Plan (monthly)")
        expect(line_item.quantity).to eq(1)
        expect(line_item.unit_amount_cents).to eq(2999)
        expect(line_item.line_type).to eq("subscription")
      end

      it "accepts custom quantity" do
        line_item = invoice.add_subscription_line_item(plan, 3)

        expect(line_item.quantity).to eq(3)
      end

      it "accepts custom period dates" do
        period_start = Date.current
        period_end = 1.month.from_now.to_date

        line_item = invoice.add_subscription_line_item(plan, 1, period_start, period_end)

        expect(line_item.period_start).to eq(period_start)
        expect(line_item.period_end).to eq(period_end)
      end

      it "uses subscription period dates when not provided" do
        # Use the subscription's existing period dates to avoid state transition overrides
        expected_start = subscription.current_period_start
        expected_end = subscription.current_period_end

        line_item = invoice.add_subscription_line_item(plan)

        expect(line_item.period_start).to be_within(1.second).of(expected_start)
        expect(line_item.period_end).to be_within(1.second).of(expected_end)
      end
    end
  end
end
