# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Plugin, type: :model do
  describe 'associations' do
    it { should belong_to(:account) }
    it { should belong_to(:creator).class_name('User') }
    it { should have_many(:workflow_node_plugins).dependent(:destroy) }
    # NOTE: ai_provider_plugin and ai_workflow_nodes associations exist in the model
    # but AiProviderPlugin and AiWorkflowNode model classes are not yet defined.
  end

  describe 'validations' do
    subject { build(:plugin) }

    it { should validate_presence_of(:plugin_id) }
    it { should validate_uniqueness_of(:plugin_id).scoped_to(:account_id) }
    it { should allow_value('valid-plugin').for(:plugin_id) }
    it { should allow_value('valid_plugin').for(:plugin_id) }
    it { should allow_value('valid.plugin').for(:plugin_id) }
    it { should_not allow_value('Invalid-Plugin!').for(:plugin_id) }
    it { should_not allow_value('plugin with spaces').for(:plugin_id) }

    it { should validate_presence_of(:name) }
    it { should validate_length_of(:name).is_at_most(255) }

    # NOTE: slug is auto-generated by generate_slug callback when name is present,
    # which defeats shoulda-matchers validate_presence_of and validate_uniqueness_of.
    it 'validates presence of slug' do
      plugin = build(:plugin, name: nil, slug: nil)
      plugin.valid?
      expect(plugin.errors[:slug]).to be_present
    end

    it 'validates uniqueness of slug within account scope' do
      account = create(:account)
      plugin1 = create(:plugin, account: account)
      plugin2 = create(:plugin, account: account)
      plugin2.slug = plugin1.slug
      # name not changed, so generate_slug callback won't fire
      expect(plugin2).not_to be_valid
      expect(plugin2.errors[:slug]).to be_present
    end

    it { should validate_presence_of(:version) }
    it { should allow_value('1.0.0').for(:version) }
    it { should allow_value('2.3.4').for(:version) }
    it { should_not allow_value('invalid').for(:version) }

    it { should validate_presence_of(:plugin_types) }
    it { should validate_inclusion_of(:status).in_array(%w[available installed error deprecated]) }
    it { should validate_inclusion_of(:source_type).in_array(%w[git npm local url marketplace]) }
    it { should validate_presence_of(:manifest) }

    describe 'custom validations' do
      describe 'validate_manifest_structure' do
        it 'is valid with proper manifest structure' do
          plugin = build(:plugin)
          expect(plugin).to be_valid
        end

        it 'is invalid with missing manifest keys' do
          plugin = build(:plugin, manifest: {})
          expect(plugin).not_to be_valid
          expect(plugin.errors[:manifest]).to be_present
        end
      end

      describe 'validate_plugin_types' do
        it 'is valid with valid plugin_types' do
          plugin = build(:plugin, plugin_types: ['workflow_node', 'ai_provider'])
          expect(plugin).to be_valid
        end

        it 'is invalid with invalid plugin_types' do
          plugin = build(:plugin, plugin_types: ['invalid_type'])
          expect(plugin).not_to be_valid
          expect(plugin.errors[:plugin_types]).to be_present
        end
      end
    end
  end

  describe 'scopes' do
    let(:account) { create(:account) }
    let!(:available_plugin) { create(:plugin, status: 'available', account: account) }
    let!(:installed_plugin) { create(:plugin, :installed, account: account) }
    let!(:verified_plugin) { create(:plugin, :verified, account: account) }
    let!(:official_plugin) { create(:plugin, :official, account: account) }
    let!(:ai_provider_plugin) { create(:plugin, :ai_provider, account: account) }
    let!(:workflow_plugin) { create(:plugin, :workflow_node, account: account) }

    describe '.active' do
      it 'returns plugins with available status' do
        expect(Plugin.active).to include(available_plugin)
        expect(Plugin.active).not_to include(installed_plugin)
      end
    end

    describe '.installed' do
      it 'returns only installed plugins' do
        expect(Plugin.installed).to include(installed_plugin)
        expect(Plugin.installed).not_to include(available_plugin)
      end
    end

    describe '.verified' do
      it 'returns only verified plugins' do
        expect(Plugin.verified).to include(verified_plugin)
        expect(Plugin.verified).not_to include(available_plugin)
      end
    end

    describe '.official' do
      it 'returns only official plugins' do
        expect(Plugin.official).to include(official_plugin)
        expect(Plugin.official).not_to include(available_plugin)
      end
    end

    describe '.by_type' do
      it 'returns plugins of specified type' do
        expect(Plugin.by_type('ai_provider')).to include(ai_provider_plugin)
        expect(Plugin.by_type('ai_provider')).not_to include(workflow_plugin)
      end
    end

    describe '.ai_providers' do
      it 'returns only AI provider plugins' do
        expect(Plugin.ai_providers).to include(ai_provider_plugin)
        expect(Plugin.ai_providers).not_to include(workflow_plugin)
      end
    end

    describe '.workflow_nodes' do
      it 'returns only workflow node plugins' do
        expect(Plugin.workflow_nodes).to include(workflow_plugin)
        expect(Plugin.workflow_nodes).not_to include(ai_provider_plugin)
      end
    end

    describe '.search_by_text' do
      it 'finds plugins by name' do
        searchable = create(:plugin, name: 'Unique Search Name', account: account)
        expect(Plugin.search_by_text('Unique Search')).to include(searchable)
      end

      it 'finds plugins by description' do
        searchable = create(:plugin, description: 'Unique Search Description', account: account)
        expect(Plugin.search_by_text('Unique Search')).to include(searchable)
      end
    end

    describe '.popular' do
      it 'orders by install_count and average_rating descending' do
        results = Plugin.popular
        expect(results).to be_a(ActiveRecord::Relation)
      end
    end

    describe '.recently_updated' do
      it 'orders by updated_at descending' do
        results = Plugin.recently_updated
        expect(results).to be_a(ActiveRecord::Relation)
      end
    end
  end

  describe 'callbacks' do
    describe '#generate_slug' do
      it 'generates a slug from the name when slug is blank' do
        plugin = build(:plugin, name: 'My Test Plugin', slug: nil)
        plugin.valid?
        expect(plugin.slug).to be_present
        expect(plugin.slug).to match(/\Amy-test-plugin/)
      end

      it 'regenerates slug when name changes' do
        plugin = create(:plugin, name: 'Original Name')
        plugin.name = 'New Name'
        plugin.valid?
        expect(plugin.slug).to match(/\Anew-name/)
      end
    end
  end

  describe 'instance methods' do
    describe '#ai_provider?' do
      it 'returns true for AI provider plugins' do
        plugin = build(:plugin, :ai_provider)
        expect(plugin.ai_provider?).to be true
      end

      it 'returns false for non-AI provider plugins' do
        plugin = build(:plugin, :workflow_node)
        expect(plugin.ai_provider?).to be false
      end
    end

    describe '#workflow_node?' do
      it 'returns true for workflow node plugins' do
        plugin = build(:plugin, :workflow_node)
        expect(plugin.workflow_node?).to be true
      end

      it 'returns false for non-workflow node plugins' do
        plugin = build(:plugin, :ai_provider)
        expect(plugin.workflow_node?).to be false
      end
    end

    describe '#integration?' do
      it 'returns true for integration plugins' do
        plugin = build(:plugin, :integration)
        expect(plugin.integration?).to be true
      end

      it 'returns false for non-integration plugins' do
        plugin = build(:plugin, :workflow_node)
        expect(plugin.integration?).to be false
      end
    end

    describe '#manifest_version' do
      it 'returns the manifest_version from manifest' do
        plugin = build(:plugin, manifest: { 'manifest_version' => '2.0', 'plugin' => { 'id' => 'test', 'name' => 'Test', 'version' => '1.0.0' }, 'plugin_types' => ['workflow_node'] })
        expect(plugin.manifest_version).to eq('2.0')
      end

      it 'returns nil when manifest_version is not set' do
        plugin = build(:plugin)
        plugin.manifest.delete('manifest_version')
        expect(plugin.manifest_version).to be_nil
      end
    end

    describe '#plugin_info' do
      it 'returns the plugin section from manifest' do
        plugin = build(:plugin)
        expect(plugin.plugin_info).to be_a(Hash)
        expect(plugin.plugin_info).to have_key('id')
      end
    end

    describe '#permissions' do
      it 'returns permissions from manifest' do
        plugin = build(:plugin, manifest: {
          'manifest_version' => '1.0',
          'plugin' => { 'id' => 'test', 'name' => 'Test', 'version' => '1.0.0' },
          'plugin_types' => ['workflow_node'],
          'permissions' => ['read', 'write']
        })
        expect(plugin.permissions).to eq(['read', 'write'])
      end

      it 'returns empty array when permissions are not set' do
        plugin = build(:plugin)
        expect(plugin.permissions).to eq([])
      end
    end

    describe '#lifecycle_hooks' do
      it 'returns lifecycle hooks from manifest' do
        plugin = build(:plugin, manifest: {
          'manifest_version' => '1.0',
          'plugin' => { 'id' => 'test', 'name' => 'Test', 'version' => '1.0.0' },
          'plugin_types' => ['workflow_node'],
          'lifecycle' => { 'on_install' => 'setup.sh' }
        })
        expect(plugin.lifecycle_hooks).to eq({ 'on_install' => 'setup.sh' })
      end

      it 'returns empty hash when lifecycle is not set' do
        plugin = build(:plugin)
        expect(plugin.lifecycle_hooks).to eq({})
      end
    end

    describe '#version_number' do
      it 'returns a Gem::Version object' do
        plugin = build(:plugin, version: '2.3.1')
        expect(plugin.version_number).to eq(Gem::Version.new('2.3.1'))
      end
    end

    describe '#compatible_with?' do
      it 'returns true when no compatibility info exists' do
        plugin = build(:plugin)
        expect(plugin.compatible_with?('1.0.0')).to be true
      end

      it 'returns true when version satisfies constraint' do
        plugin = build(:plugin, manifest: {
          'manifest_version' => '1.0',
          'plugin' => { 'id' => 'test', 'name' => 'Test', 'version' => '1.0.0' },
          'plugin_types' => ['workflow_node'],
          'compatibility' => { 'powernode_version' => '>= 1.0.0' }
        })
        expect(plugin.compatible_with?('2.0.0')).to be true
      end

      it 'returns false when version does not satisfy constraint' do
        plugin = build(:plugin, manifest: {
          'manifest_version' => '1.0',
          'plugin' => { 'id' => 'test', 'name' => 'Test', 'version' => '1.0.0' },
          'plugin_types' => ['workflow_node'],
          'compatibility' => { 'powernode_version' => '>= 3.0.0' }
        })
        expect(plugin.compatible_with?('2.0.0')).to be false
      end
    end
  end
end
