# frozen_string_literal: true

require 'rails_helper'

RSpec.describe UsageMeter, type: :model do
  describe 'associations' do
    it { is_expected.to have_many(:usage_events).dependent(:destroy) }
    it { is_expected.to have_many(:usage_summaries).dependent(:destroy) }
    it { is_expected.to have_many(:usage_quotas).dependent(:destroy) }
  end

  describe 'validations' do
    subject { build(:usage_meter) }

    it { is_expected.to validate_presence_of(:name) }
    it { is_expected.to validate_length_of(:name).is_at_least(2).is_at_most(100) }
    # NOTE: slug is auto-generated by generate_slug callback when blank,
    # defeating shoulda-matchers validate_presence_of. Test uniqueness only.
    it { is_expected.to validate_uniqueness_of(:slug) }
    it { is_expected.to allow_value('api-calls').for(:slug) }
    it { is_expected.to allow_value('storage_gb').for(:slug) }
    it { is_expected.to allow_value('bandwidth-used').for(:slug) }
    it { is_expected.not_to allow_value('Invalid Slug').for(:slug) }
    it { is_expected.not_to allow_value('slug with spaces').for(:slug) }
    it { is_expected.not_to allow_value('UPPERCASE').for(:slug) }
    it { is_expected.to validate_presence_of(:unit_name) }
    it { is_expected.to validate_presence_of(:aggregation_type) }
    it do
      is_expected.to validate_inclusion_of(:aggregation_type)
        .in_array(%w[sum max count last average])
    end
    it { is_expected.to validate_presence_of(:billing_model) }
    it do
      is_expected.to validate_inclusion_of(:billing_model)
        .in_array(%w[tiered volume package flat per_unit])
    end
    it { is_expected.to validate_presence_of(:reset_period) }
    it do
      is_expected.to validate_inclusion_of(:reset_period)
        .in_array(%w[never daily weekly monthly yearly billing_period])
    end
  end

  describe 'callbacks' do
    describe 'generate_slug' do
      it 'generates a slug from the name when slug is blank' do
        meter = build(:usage_meter, name: 'API Calls', slug: nil)
        meter.valid?
        expect(meter.slug).to eq('api_calls')
      end

      it 'does not overwrite an existing slug' do
        meter = build(:usage_meter, name: 'API Calls', slug: 'custom-slug')
        meter.valid?
        expect(meter.slug).to eq('custom-slug')
      end
    end
  end

  describe 'scopes' do
    describe '.active' do
      it 'returns only active meters' do
        active = create(:usage_meter, is_active: true)
        inactive = create(:usage_meter, is_active: false)

        expect(UsageMeter.active).to include(active)
        expect(UsageMeter.active).not_to include(inactive)
      end
    end

    describe '.billable' do
      it 'returns only billable meters' do
        billable = create(:usage_meter, is_billable: true)
        non_billable = create(:usage_meter, is_billable: false)

        expect(UsageMeter.billable).to include(billable)
        expect(UsageMeter.billable).not_to include(non_billable)
      end
    end
  end

  describe 'instance methods' do
    describe '#active?' do
      it 'returns true when is_active is true' do
        meter = build(:usage_meter, is_active: true)
        expect(meter.active?).to be true
      end

      it 'returns false when is_active is false' do
        meter = build(:usage_meter, is_active: false)
        expect(meter.active?).to be false
      end
    end

    describe '#billable?' do
      it 'returns true when is_billable is true' do
        meter = build(:usage_meter, is_billable: true)
        expect(meter.billable?).to be true
      end

      it 'returns false when is_billable is false' do
        meter = build(:usage_meter, is_billable: false)
        expect(meter.billable?).to be false
      end
    end

    describe '#aggregate_events' do
      let(:account) { create(:account) }

      context 'with sum aggregation' do
        it 'sums the quantity of events' do
          meter = create(:usage_meter, aggregation_type: 'sum')
          create(:usage_event, account: account, usage_meter: meter, quantity: 10)
          create(:usage_event, account: account, usage_meter: meter, quantity: 20)
          create(:usage_event, account: account, usage_meter: meter, quantity: 15)

          events = meter.usage_events
          result = meter.aggregate_events(events)

          expect(result).to eq(45)
        end
      end

      context 'with count aggregation' do
        it 'counts the number of events' do
          meter = create(:usage_meter, aggregation_type: 'count')
          create(:usage_event, account: account, usage_meter: meter, quantity: 10)
          create(:usage_event, account: account, usage_meter: meter, quantity: 20)
          create(:usage_event, account: account, usage_meter: meter, quantity: 15)

          events = meter.usage_events
          result = meter.aggregate_events(events)

          expect(result).to eq(3)
        end
      end

      context 'with max aggregation' do
        it 'returns the maximum quantity' do
          meter = create(:usage_meter, aggregation_type: 'max')
          create(:usage_event, account: account, usage_meter: meter, quantity: 10)
          create(:usage_event, account: account, usage_meter: meter, quantity: 50)
          create(:usage_event, account: account, usage_meter: meter, quantity: 15)

          events = meter.usage_events
          result = meter.aggregate_events(events)

          expect(result).to eq(50)
        end
      end

      context 'with empty events' do
        it 'returns 0' do
          meter = create(:usage_meter, aggregation_type: 'sum')
          events = meter.usage_events
          result = meter.aggregate_events(events)

          expect(result).to eq(0)
        end
      end
    end

    describe '#calculate_cost' do
      context 'with flat billing model' do
        it 'returns flat price regardless of quantity' do
          meter = create(:usage_meter, :flat_rate)
          expect(meter.calculate_cost(500)).to eq(99.0)
        end
      end

      context 'with per_unit billing model' do
        it 'calculates cost as quantity times unit price' do
          meter = create(:usage_meter, :per_unit)
          cost = meter.calculate_cost(200)
          expect(cost).to eq(2.0) # 200 * 0.01
        end
      end

      context 'with tiered billing model' do
        it 'calculates cost based on tiered pricing' do
          meter = create(:usage_meter,
            billing_model: 'tiered',
            pricing_tiers: [
              { "from" => 0, "to" => 100, "price_per_unit" => 0.10 },
              { "from" => 100, "to" => 500, "price_per_unit" => 0.05 },
              { "from" => 500, "price_per_unit" => 0.02 }
            ]
          )

          # First 100 at $0.10 = $10
          # Next 400 (100-500) at $0.05 = $20
          # Remaining 100 (500-600) at $0.02 = $2
          # Total: $32
          cost = meter.calculate_cost(600)
          expect(cost).to eq(32.0)
        end
      end

      context 'with volume billing model' do
        it 'applies one rate to all units based on total volume' do
          meter = create(:usage_meter, :volume)
          # volume tiers: 0 => 0.10, 100 => 0.08, 1000 => 0.05
          # 500 units => falls in the "from 100" tier => 500 * 0.08
          cost = meter.calculate_cost(500)
          expect(cost).to eq(40.0)
        end
      end

      context 'with package billing model' do
        it 'calculates cost based on packages needed' do
          meter = create(:usage_meter, :package)
          # package_size: 100, price: 10.00
          # 250 units => ceil(250/100) = 3 packages => 3 * 10 = 30
          cost = meter.calculate_cost(250)
          expect(cost).to eq(30.0)
        end
      end

      context 'when not billable' do
        it 'returns 0' do
          meter = create(:usage_meter, :non_billable)
          expect(meter.calculate_cost(500)).to eq(0.0)
        end
      end
    end

    describe '#period_dates' do
      it 'returns start and end dates for monthly reset period' do
        travel_to(Time.current) do
          meter = create(:usage_meter, reset_period: 'monthly')

          start_date, end_date = meter.period_dates

          expect(start_date).to eq(Date.current.beginning_of_month)
          expect(end_date).to eq(Date.current.end_of_month)
        end
      end

      it 'returns start and end dates for weekly reset period' do
        travel_to(Time.current) do
          meter = create(:usage_meter, reset_period: 'weekly')

          start_date, end_date = meter.period_dates

          expect(start_date).to eq(Date.current.beginning_of_week)
          expect(end_date).to eq(Date.current.end_of_week)
        end
      end

      it 'returns start and end dates for daily reset period' do
        travel_to(Time.current) do
          meter = create(:usage_meter, reset_period: 'daily')

          start_date, end_date = meter.period_dates

          expect(start_date).to eq(Date.current.beginning_of_day)
          expect(end_date).to eq(Date.current.end_of_day)
        end
      end

      it 'returns nil dates for never reset period' do
        meter = create(:usage_meter, reset_period: 'never')

        start_date, end_date = meter.period_dates

        expect(start_date).to be_nil
        expect(end_date).to be_nil
      end
    end

    describe '#summary' do
      it 'returns a hash with meter summary information' do
        meter = create(:usage_meter)
        result = meter.summary

        expect(result).to be_a(Hash)
        expect(result[:id]).to eq(meter.id)
        expect(result[:name]).to eq(meter.name)
        expect(result[:slug]).to eq(meter.slug)
        expect(result[:unit_name]).to eq(meter.unit_name)
        expect(result[:aggregation_type]).to eq(meter.aggregation_type)
        expect(result[:billing_model]).to eq(meter.billing_model)
        expect(result[:reset_period]).to eq(meter.reset_period)
        expect(result[:is_active]).to eq(meter.is_active)
        expect(result[:is_billable]).to eq(meter.is_billable)
        expect(result[:pricing_tiers]).to eq(meter.pricing_tiers)
      end
    end
  end
end
