# frozen_string_literal: true

class ReviewMediaAttachment < ApplicationRecord
  include AuditLogging
  
  # Associations
  belongs_to :app_review
  
  # Validations
  validates :media_type, presence: true, inclusion: { 
    in: %w[image video],
    message: "must be image or video"
  }
  validates :file_name, presence: true, length: { maximum: 255 }
  validates :file_path, presence: true, length: { maximum: 500 }
  validates :file_size, numericality: { greater_than: 0 }, allow_nil: true
  validates :mime_type, presence: true, length: { maximum: 100 }
  validates :processing_status, presence: true, inclusion: { 
    in: %w[pending processing completed failed],
    message: "must be pending, processing, completed, or failed"
  }
  validates :moderation_status, presence: true, inclusion: { 
    in: %w[pending approved rejected],
    message: "must be pending, approved, or rejected"
  }
  validates :sort_order, numericality: { greater_than_or_equal_to: 0 }
  validates :alt_text, length: { maximum: 500 }
  
  # Scopes
  scope :images, -> { where(media_type: 'image') }
  scope :videos, -> { where(media_type: 'video') }
  scope :approved, -> { where(moderation_status: 'approved') }
  scope :pending_moderation, -> { where(moderation_status: 'pending') }
  scope :rejected, -> { where(moderation_status: 'rejected') }
  scope :processing_completed, -> { where(processing_status: 'completed') }
  scope :processing_failed, -> { where(processing_status: 'failed') }
  scope :publicly_visible, -> { approved.processing_completed }
  scope :ordered, -> { order(:sort_order, :created_at) }
  
  # Callbacks
  after_create :log_media_uploaded
  after_update :log_processing_status_changed, if: :saved_change_to_processing_status?
  after_update :log_moderation_status_changed, if: :saved_change_to_moderation_status?
  
  # Status methods
  def processing_pending?
    processing_status == 'pending'
  end
  
  def processing_in_progress?
    processing_status == 'processing'
  end
  
  def processing_completed?
    processing_status == 'completed'
  end
  
  def processing_failed?
    processing_status == 'failed'
  end
  
  def moderation_pending?
    moderation_status == 'pending'
  end
  
  def moderation_approved?
    moderation_status == 'approved'
  end
  
  def moderation_rejected?
    moderation_status == 'rejected'
  end
  
  def publicly_visible?
    processing_completed? && moderation_approved?
  end
  
  # Media type methods
  def image?
    media_type == 'image'
  end
  
  def video?
    media_type == 'video'
  end
  
  # File methods
  def file_extension
    File.extname(file_name).downcase
  end
  
  def file_size_mb
    return 0 unless file_size
    
    (file_size.to_f / 1024 / 1024).round(2)
  end
  
  def file_size_formatted
    return 'Unknown' unless file_size
    
    if file_size < 1024
      "#{file_size} bytes"
    elsif file_size < 1024 * 1024
      "#{(file_size / 1024.0).round(1)} KB"
    else
      "#{file_size_mb} MB"
    end
  end
  
  # Processing methods
  def mark_processing!
    update!(processing_status: 'processing')
    log_processing_started
  end
  
  def mark_processing_completed!
    update!(processing_status: 'completed')
    log_processing_completed
  end
  
  def mark_processing_failed!(error_message = nil)
    update!(processing_status: 'failed')
    metadata['error_message'] = error_message if error_message
    metadata['failed_at'] = Time.current.iso8601
    save!
    log_processing_failed(error_message)
  end
  
  # Moderation methods
  def approve!(moderator = nil)
    update!(moderation_status: 'approved')
    metadata['approved_by'] = moderator.id if moderator
    metadata['approved_at'] = Time.current.iso8601
    save!
    log_moderation_approved(moderator)
  end
  
  def reject!(reason = nil, moderator = nil)
    update!(moderation_status: 'rejected')
    metadata['rejection_reason'] = reason if reason
    metadata['rejected_by'] = moderator.id if moderator
    metadata['rejected_at'] = Time.current.iso8601
    save!
    log_moderation_rejected(reason, moderator)
  end
  
  # URL methods (these would typically integrate with your file storage system)
  def thumbnail_url
    return nil unless image? && processing_completed?
    
    # This would typically be generated by your image processing system
    file_path.gsub(/(\.\w+)$/, '_thumb\1')
  end
  
  def full_url
    return nil unless processing_completed?
    
    file_path
  end
  
  # Display methods
  def status_display
    "#{processing_status.humanize} (#{moderation_status.humanize})"
  end
  
  def media_type_display
    media_type.humanize
  end
  
  private
  
  def log_media_uploaded
    Rails.logger.info "Media uploaded for review #{app_review_id}: #{media_type} #{file_name} (#{file_size_formatted})"
  end
  
  def log_processing_status_changed
    Rails.logger.info "Media processing status changed: #{id} from #{processing_status_before_last_save} to #{processing_status}"
  end
  
  def log_moderation_status_changed
    Rails.logger.info "Media moderation status changed: #{id} from #{moderation_status_before_last_save} to #{moderation_status}"
  end
  
  def log_processing_started
    Rails.logger.info "Media processing started: #{id}"
  end
  
  def log_processing_completed
    Rails.logger.info "Media processing completed: #{id}"
  end
  
  def log_processing_failed(error_message)
    Rails.logger.info "Media processing failed: #{id} - #{error_message}"
  end
  
  def log_moderation_approved(moderator)
    moderator_info = moderator ? "by #{moderator.id}" : "automatically"
    Rails.logger.info "Media approved #{moderator_info}: #{id}"
  end
  
  def log_moderation_rejected(reason, moderator)
    moderator_info = moderator ? "by #{moderator.id}" : "automatically"
    Rails.logger.info "Media rejected #{moderator_info}: #{id} - #{reason}"
  end
end