# frozen_string_literal: true

module Marketing
  class CampaignContentGeneratorService
    class GenerationError < StandardError; end

    def initialize(campaign)
      @campaign = campaign
    end

    # Generate AI-powered content for a campaign
    # Returns array of created CampaignContent records
    def generate(channel:, variant_count: 1, options: {})
      validate_channel!(channel)

      contents = []
      variant_count.times do |i|
        content = build_content(channel, i + 1, options)
        content.save!
        contents << content
      end

      contents
    rescue ActiveRecord::RecordInvalid => e
      raise GenerationError, "Failed to generate content: #{e.message}"
    end

    # Generate content for multiple channels at once
    def generate_multi_channel(channels:, variant_count: 1, options: {})
      results = {}

      channels.each do |channel|
        results[channel] = generate(
          channel: channel,
          variant_count: variant_count,
          options: options
        )
      end

      results
    end

    private

    def validate_channel!(channel)
      return if Marketing::CampaignContent::CHANNELS.include?(channel)

      raise GenerationError, "Unsupported channel: #{channel}"
    end

    def build_content(channel, variant_number, options)
      existing_count = @campaign.campaign_contents.by_channel(channel).count

      @campaign.campaign_contents.build(
        channel: channel,
        variant_name: "#{channel.titleize} Variant #{existing_count + variant_number}",
        subject: generate_subject(channel, options),
        preview_text: generate_preview_text(channel, options),
        body: generate_body(channel, options),
        cta_text: options[:cta_text] || default_cta_text(channel),
        cta_url: options[:cta_url],
        ai_generated: true,
        status: "draft",
        platform_specific: platform_defaults(channel)
      )
    end

    def generate_subject(channel, options)
      return options[:subject] if options[:subject].present?

      # AI generation stub - would integrate with AI provider
      "#{@campaign.name} - #{channel.titleize} Update"
    end

    def generate_preview_text(channel, options)
      return options[:preview_text] if options[:preview_text].present?

      "Check out the latest from #{@campaign.name}"
    end

    def generate_body(channel, options)
      return options[:body] if options[:body].present?

      # AI generation stub - would integrate with AI provider
      <<~BODY
        [AI Generated Content for #{channel.titleize}]

        Campaign: #{@campaign.name}
        Type: #{@campaign.campaign_type}

        This is placeholder content that would be generated by an AI provider.
        Target audience: #{@campaign.target_audience.to_json}
      BODY
    end

    def default_cta_text(channel)
      case channel
      when "email" then "Learn More"
      when "twitter" then "Read More"
      when "linkedin" then "See Details"
      when "facebook", "instagram" then "Shop Now"
      else "Click Here"
      end
    end

    def platform_defaults(channel)
      case channel
      when "twitter"
        { max_length: 280, hashtags: [] }
      when "linkedin"
        { max_length: 3000, article_mode: false }
      when "instagram"
        { max_hashtags: 30, story_mode: false }
      when "facebook"
        { max_length: 63206, link_preview: true }
      else
        {}
      end
    end
  end
end
