/// <reference types="cypress" />

/**
 * Unified Login Commands
 *
 * Standardized login commands to replace duplicated login code across test files.
 * Uses Cypress session caching for performance optimization.
 */

export interface LoginOptions {
  /** Skip navigation to dashboard after login (default: false) */
  skipDashboardNav?: boolean;
  /** Custom URL to visit after login (default: /app/dashboard) */
  redirectUrl?: string;
  /** Wait for page load after redirect (default: true) */
  waitForLoad?: boolean;
}

export interface RoleCredentials {
  email: string;
  password: string;
}

declare global {
  namespace Cypress {
    interface Chainable {
      /**
       * Login as the demo user (most common use case)
       * Uses session caching for faster test execution
       * @example cy.loginAsDemo()
       * @example cy.loginAsDemo({ skipDashboardNav: true })
       */
      loginAsDemo(options?: LoginOptions): Chainable<void>;

      /**
       * Login as a specific role
       * @example cy.loginAsRole('admin')
       * @example cy.loginAsRole('billing.manager')
       */
      loginAsRole(role: string, options?: LoginOptions): Chainable<void>;

      /**
       * Login via API (bypasses UI for faster tests)
       * @example cy.loginViaAPI('user@example.com', 'password')
       */
      loginViaAPI(email: string, password: string): Chainable<void>;

      /**
       * Login via UI with any credentials
       * @example cy.loginViaUI('user@example.com', 'password')
       */
      loginViaUI(email: string, password: string, options?: LoginOptions): Chainable<void>;

      /**
       * Standard test setup: clear data, setup intercepts, login
       * @example cy.standardTestSetup()
       * @example cy.standardTestSetup({ role: 'admin' })
       */
      standardTestSetup(options?: { role?: string; intercepts?: string[] }): Chainable<void>;
    }
  }
}

// Get credentials from environment (flat structure for all roles)
// Environment variables are loaded from test-credentials.json via cypress.config.ts
// Generated by: rails db:seed (includes cypress_test_users.rb)
const getCredentials = (role?: string): RoleCredentials => {
  // Map role names to environment variable prefixes
  const roleMapping: Record<string, string> = {
    'admin': 'ADMIN',
    'super_admin': 'ADMIN',
    'manager': 'MANAGER',
    'billing': 'BILLING',
    'billing.manager': 'BILLING',
    'billing_manager': 'BILLING',
    'member': 'MEMBER',
    'account.member': 'MEMBER',
    'demo': 'DEMO',
  };

  // Determine which prefix to use
  const prefix = role ? (roleMapping[role.toLowerCase()] || 'DEMO') : 'DEMO';

  // Get credentials using flat structure
  const email = Cypress.env(`${prefix}_EMAIL`);
  const password = Cypress.env(`${prefix}_PASSWORD`);

  if (email && password) {
    return { email, password };
  }

  // Fallback: These should never be used in practice
  // The seed script generates test-credentials.json which is loaded via cypress.config.ts
  console.warn(`⚠️ Using fallback credentials for ${prefix}. Run "rails db:seed" to generate test credentials.`);
  return {
    email: 'demo@powernode.org',
    password: 'CREDENTIALS_NOT_LOADED',
  };
};

// Login as demo user with session caching (API-first for speed)
Cypress.Commands.add('loginAsDemo', (options: LoginOptions = {}) => {
  const { skipDashboardNav = false, redirectUrl, waitForLoad = true } = options;
  const credentials = getCredentials();
  const apiUrl = Cypress.env('apiUrl') || 'http://localhost:3000/api/v1';

  cy.session(
    ['demo-user', credentials.email],
    () => {
      // Try API login first (much faster than UI)
      cy.request({
        method: 'POST',
        url: `${apiUrl}/auth/login`,
        body: { email: credentials.email, password: credentials.password },
        failOnStatusCode: false,
      }).then((response) => {
        if (response.status === 200 && response.body?.data?.access_token) {
          // API login succeeded - store tokens
          cy.window().then((win) => {
            win.localStorage.setItem('access_token', response.body.data.access_token);
            if (response.body.data.refresh_token) {
              win.localStorage.setItem('refresh_token', response.body.data.refresh_token);
            }
          });
        } else {
          // Fallback to UI login if API fails
          cy.visit('/login');
          cy.get('[data-testid="email-input"]', { timeout: 5000 })
            .should('be.visible')
            .clear()
            .type(credentials.email);
          cy.get('[data-testid="password-input"]').clear().type(credentials.password);
          cy.get('[data-testid="login-submit-btn"]').should('not.be.disabled').click();
          cy.url({ timeout: 10000 }).should('match', /\/(app|dashboard)/);
        }
      });
    },
    {
      validate: () => {
        // Validate session by checking localStorage
        cy.window().then((win) => {
          const token = win.localStorage.getItem('access_token');
          expect(token).to.exist;
        });
      },
    }
  );

  // Navigate after session restoration
  if (!skipDashboardNav) {
    const targetUrl = redirectUrl || '/app/dashboard';
    cy.visit(targetUrl);
    if (waitForLoad) {
      cy.waitForPageLoad();
    }
  }
});

// Login as specific role (API-first for speed)
Cypress.Commands.add('loginAsRole', (role: string, options: LoginOptions = {}) => {
  const { skipDashboardNav = false, redirectUrl, waitForLoad = true } = options;
  const credentials = getCredentials(role);
  const apiUrl = Cypress.env('apiUrl') || 'http://localhost:3000/api/v1';

  cy.session(
    ['role-user', role, credentials.email],
    () => {
      // Try API login first (much faster than UI)
      cy.request({
        method: 'POST',
        url: `${apiUrl}/auth/login`,
        body: { email: credentials.email, password: credentials.password },
        failOnStatusCode: false,
      }).then((response) => {
        if (response.status === 200 && response.body?.data?.access_token) {
          // API login succeeded - store tokens
          cy.window().then((win) => {
            win.localStorage.setItem('access_token', response.body.data.access_token);
            if (response.body.data.refresh_token) {
              win.localStorage.setItem('refresh_token', response.body.data.refresh_token);
            }
          });
        } else {
          // Fallback to UI login if API fails
          cy.visit('/login');
          cy.get('[data-testid="email-input"]', { timeout: 5000 })
            .should('be.visible')
            .clear()
            .type(credentials.email);
          cy.get('[data-testid="password-input"]').clear().type(credentials.password);
          cy.get('[data-testid="login-submit-btn"]').should('not.be.disabled').click();
          cy.url({ timeout: 10000 }).should('match', /\/(app|dashboard)/);
        }
      });
    },
    {
      validate: () => {
        cy.window().then((win) => {
          const token = win.localStorage.getItem('access_token');
          expect(token).to.exist;
        });
      },
    }
  );

  if (!skipDashboardNav) {
    const targetUrl = redirectUrl || '/app/dashboard';
    cy.visit(targetUrl);
    if (waitForLoad) {
      cy.waitForPageLoad();
    }
  }
});

// Login via API (fastest, bypasses UI)
Cypress.Commands.add('loginViaAPI', (email: string, password: string) => {
  const apiUrl = Cypress.env('apiUrl') || 'http://localhost:3000/api/v1';

  cy.request({
    method: 'POST',
    url: `${apiUrl}/auth/login`,
    body: { email, password },
    failOnStatusCode: false,
  }).then((response) => {
    if (response.status === 200 && response.body?.data?.access_token) {
      cy.window().then((win) => {
        win.localStorage.setItem('access_token', response.body.data.access_token);
        if (response.body.data.refresh_token) {
          win.localStorage.setItem('refresh_token', response.body.data.refresh_token);
        }
      });
    } else {
      // Fallback to UI login if API fails
      cy.loginViaUI(email, password);
    }
  });
});

// Login via UI with any credentials
Cypress.Commands.add('loginViaUI', (email: string, password: string, options: LoginOptions = {}) => {
  const { skipDashboardNav = false, redirectUrl, waitForLoad = true } = options;

  cy.visit('/login');
  cy.get('[data-testid="email-input"]', { timeout: 10000 })
    .should('be.visible')
    .clear()
    .type(email);
  cy.get('[data-testid="password-input"]').clear().type(password);
  cy.get('[data-testid="login-submit-btn"]').should('not.be.disabled').click();
  cy.url({ timeout: 15000 }).should('match', /\/(app|dashboard)/);

  if (!skipDashboardNav && redirectUrl) {
    cy.visit(redirectUrl);
    if (waitForLoad) {
      cy.waitForPageLoad();
    }
  }
});

// Standard test setup (combines common beforeEach operations)
Cypress.Commands.add('standardTestSetup', (options = {}) => {
  const { role, intercepts = [] } = options;

  // Clear application data
  cy.clearAppData();

  // Setup common API intercepts
  cy.setupApiIntercepts();

  // Setup feature-specific intercepts
  intercepts.forEach((interceptType) => {
    switch (interceptType) {
      case 'ai':
        cy.setupAiIntercepts();
        break;
      case 'admin':
        cy.setupAdminIntercepts();
        break;
      case 'devops':
        cy.setupDevopsIntercepts();
        break;
      case 'system':
        cy.setupSystemIntercepts();
        break;
      case 'marketplace':
        cy.setupMarketplaceIntercepts();
        break;
      case 'content':
        cy.setupContentIntercepts();
        break;
      case 'privacy':
        cy.setupPrivacyIntercepts();
        break;
      case 'supply-chain':
        cy.setupSupplyChainIntercepts();
        break;
    }
  });

  // Login with appropriate role
  if (role) {
    cy.loginAsRole(role);
  } else {
    cy.loginAsDemo();
  }
});

export {};
