# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Devops::DockerHost, type: :model do
  subject(:docker_host) { build(:devops_docker_host) }

  describe 'associations' do
    it { is_expected.to belong_to(:account) }
    it { is_expected.to have_many(:docker_containers).dependent(:destroy) }
    it { is_expected.to have_many(:docker_images).dependent(:destroy) }
    it { is_expected.to have_many(:docker_events).dependent(:destroy) }
    it { is_expected.to have_many(:docker_activities).dependent(:destroy) }
  end

  describe 'validations' do
    it { is_expected.to validate_presence_of(:name) }
    # slug presence validated but auto-generated by callback, tested in callbacks section
    it { is_expected.to validate_presence_of(:api_endpoint) }
    it { is_expected.to validate_presence_of(:environment) }
    it { is_expected.to validate_presence_of(:status) }

    context 'name uniqueness scoped to account' do
      let(:account) { create(:account) }

      before { create(:devops_docker_host, name: 'My Host', account: account) }

      it 'rejects duplicate names within the same account' do
        duplicate = build(:devops_docker_host, name: 'My Host', account: account)
        expect(duplicate).not_to be_valid
        expect(duplicate.errors[:name]).to include('has already been taken')
      end

      it 'allows same name in a different account' do
        other_account = create(:account)
        host = build(:devops_docker_host, name: 'My Host', account: other_account)
        expect(host).to be_valid
      end
    end

    context 'slug uniqueness' do
      before { create(:devops_docker_host, slug: 'unique-slug') }

      it 'rejects duplicate slugs' do
        duplicate = build(:devops_docker_host, slug: 'unique-slug')
        expect(duplicate).not_to be_valid
        expect(duplicate.errors[:slug]).to include('has already been taken')
      end
    end

    context 'slug format' do
      it 'accepts valid slugs' do
        docker_host.slug = 'my-docker-host-1'
        expect(docker_host).to be_valid
      end

      it 'rejects slugs with invalid characters' do
        docker_host.slug = 'My Docker Host!'
        expect(docker_host).not_to be_valid
        expect(docker_host.errors[:slug]).to be_present
      end
    end

    context 'api_endpoint format' do
      it 'accepts valid https endpoints' do
        docker_host.api_endpoint = 'https://docker.example.com:2376'
        expect(docker_host).to be_valid
      end

      it 'accepts valid http endpoints' do
        docker_host.api_endpoint = 'http://localhost:2375'
        expect(docker_host).to be_valid
      end

      it 'rejects invalid endpoints' do
        docker_host.api_endpoint = 'not-a-url'
        expect(docker_host).not_to be_valid
        expect(docker_host.errors[:api_endpoint]).to be_present
      end
    end

    context 'environment inclusion' do
      it 'accepts valid environments' do
        %w[staging production development custom].each do |env|
          docker_host.environment = env
          expect(docker_host).to be_valid
        end
      end

      it 'rejects invalid environments' do
        docker_host.environment = 'invalid'
        expect(docker_host).not_to be_valid
        expect(docker_host.errors[:environment]).to be_present
      end
    end

    context 'status inclusion' do
      it 'accepts valid statuses' do
        %w[pending connected disconnected error maintenance].each do |s|
          docker_host.status = s
          expect(docker_host).to be_valid
        end
      end

      it 'rejects invalid statuses' do
        docker_host.status = 'invalid'
        expect(docker_host).not_to be_valid
        expect(docker_host.errors[:status]).to be_present
      end
    end

    context 'sync_interval_seconds numericality' do
      it 'accepts values within range' do
        docker_host.sync_interval_seconds = 30
        expect(docker_host).to be_valid

        docker_host.sync_interval_seconds = 3600
        expect(docker_host).to be_valid
      end

      it 'rejects values below minimum' do
        docker_host.sync_interval_seconds = 29
        expect(docker_host).not_to be_valid
      end

      it 'rejects values above maximum' do
        docker_host.sync_interval_seconds = 3601
        expect(docker_host).not_to be_valid
      end
    end
  end

  describe 'scopes' do
    let!(:connected_host) { create(:devops_docker_host, :connected, auto_sync: true) }
    let!(:disconnected_host) { create(:devops_docker_host, :disconnected) }
    let!(:dev_host) { create(:devops_docker_host, environment: 'development') }
    let!(:prod_host) { create(:devops_docker_host, environment: 'production') }

    describe '.connected' do
      it 'returns only connected hosts' do
        expect(described_class.connected).to include(connected_host)
        expect(described_class.connected).not_to include(disconnected_host)
      end
    end

    describe '.auto_syncable' do
      it 'returns connected hosts with auto_sync enabled' do
        expect(described_class.auto_syncable).to include(connected_host)
        expect(described_class.auto_syncable).not_to include(disconnected_host)
      end
    end

    describe '.by_environment' do
      it 'filters by environment' do
        expect(described_class.by_environment('production')).to include(prod_host)
        expect(described_class.by_environment('production')).not_to include(dev_host)
      end
    end
  end

  describe 'callbacks' do
    describe 'generate_slug on create' do
      it 'generates slug from name when slug is blank' do
        host = build(:devops_docker_host, name: 'My Docker Host', slug: nil)
        host.valid?
        expect(host.slug).to eq('my-docker-host')
      end

      it 'does not overwrite an existing slug' do
        host = build(:devops_docker_host, name: 'My Docker Host', slug: 'custom-slug')
        host.valid?
        expect(host.slug).to eq('custom-slug')
      end

      it 'generates unique slug when duplicate exists' do
        create(:devops_docker_host, slug: 'my-docker-host')
        host = build(:devops_docker_host, name: 'My Docker Host', slug: nil)
        host.valid?
        expect(host.slug).to start_with('my-docker-host')
      end
    end
  end

  describe 'instance methods' do
    describe '#record_success!' do
      it 'sets status to connected, resets failures, and sets last_synced_at' do
        host = create(:devops_docker_host, status: 'pending', consecutive_failures: 3)
        host.record_success!
        host.reload

        expect(host.status).to eq('connected')
        expect(host.consecutive_failures).to eq(0)
        expect(host.last_synced_at).to be_within(2.seconds).of(Time.current)
      end
    end

    describe '#record_failure!' do
      it 'increments consecutive failures' do
        host = create(:devops_docker_host, :connected, consecutive_failures: 0)
        host.record_failure!
        host.reload

        expect(host.consecutive_failures).to eq(1)
      end

      it 'sets status to error when reaching MAX_CONSECUTIVE_FAILURES' do
        host = create(:devops_docker_host, :connected, consecutive_failures: 4)
        host.record_failure!
        host.reload

        expect(host.consecutive_failures).to eq(5)
        expect(host.status).to eq('error')
      end

      it 'keeps current status below MAX_CONSECUTIVE_FAILURES' do
        host = create(:devops_docker_host, :connected, consecutive_failures: 2)
        host.record_failure!
        host.reload

        expect(host.status).to eq('connected')
      end
    end

    describe '#host_summary' do
      it 'returns a hash with summary fields' do
        host = create(:devops_docker_host, :connected)
        summary = host.host_summary

        expect(summary).to include(
          id: host.id,
          name: host.name,
          slug: host.slug,
          api_endpoint: host.api_endpoint,
          environment: host.environment,
          status: 'connected'
        )
      end
    end

    describe '#host_details' do
      it 'returns summary merged with detail fields' do
        host = create(:devops_docker_host, :connected)
        details = host.host_details

        expect(details).to include(:id, :name, :slug, :status)
        expect(details).to include(:description, :api_version, :docker_version, :os_type,
                                   :architecture, :kernel_version, :memory_bytes, :cpu_count,
                                   :storage_bytes, :sync_interval_seconds, :consecutive_failures,
                                   :metadata, :created_at, :updated_at)
      end
    end
  end
end
