# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Ai::WorkflowTemplateInstallation, type: :model do
  subject(:installation) { build(:ai_workflow_template_installation) }

  describe 'associations' do
    it { is_expected.to belong_to(:template) }
    it { is_expected.to belong_to(:workflow) }
    it { is_expected.to belong_to(:account) }
    it { is_expected.to belong_to(:installed_by_user).class_name('User') }
  end

  describe 'validations' do
    # Note: installation_id and template_version are auto-generated by callbacks
    # so we don't test presence validation directly

    context 'uniqueness validation' do
      it 'validates unique installation per template per account' do
        existing = create(:ai_workflow_template_installation)
        duplicate = build(:ai_workflow_template_installation,
                         template: existing.template,
                         account: existing.account)

        expect(duplicate).not_to be_valid
        expect(duplicate.errors[:ai_workflow_template_id]).to include('has already been installed for this account')
      end

      it 'allows same template in different accounts' do
        template = create(:ai_workflow_template)
        account1 = create(:account)
        account2 = create(:account)
        workflow1 = create(:ai_workflow, account: account1)
        workflow2 = create(:ai_workflow, account: account2)
        user1 = create(:user, account: account1)
        user2 = create(:user, account: account2)

        create(:ai_workflow_template_installation,
               template: template,
               workflow: workflow1,
               account: account1,
               installed_by_user: user1)

        duplicate = build(:ai_workflow_template_installation,
                         template: template,
                         workflow: workflow2,
                         account: account2,
                         installed_by_user: user2)

        expect(duplicate).to be_valid
      end

      it 'validates uniqueness of installation_id' do
        existing = create(:ai_workflow_template_installation)
        duplicate = build(:ai_workflow_template_installation, installation_id: existing.installation_id)

        expect(duplicate).not_to be_valid
        expect(duplicate.errors[:installation_id]).to include('has already been taken')
      end
    end
  end

  describe 'scopes' do
    describe '.recent' do
      let!(:old_installation) { create(:ai_workflow_template_installation, created_at: 1.month.ago) }
      let!(:new_installation) { create(:ai_workflow_template_installation, created_at: 1.hour.ago) }

      it 'orders installations by created_at descending' do
        expect(described_class.recent.first).to eq(new_installation)
      end
    end

    describe '.for_template' do
      let(:template1) { create(:ai_workflow_template) }
      let(:template2) { create(:ai_workflow_template) }
      let!(:installation1) { create(:ai_workflow_template_installation, template: template1) }
      let!(:installation2) { create(:ai_workflow_template_installation, template: template2) }

      it 'filters installations by template' do
        expect(described_class.for_template(template1.id)).to include(installation1)
        expect(described_class.for_template(template1.id)).not_to include(installation2)
      end
    end

    describe '.for_account' do
      let(:account1) { create(:account) }
      let(:account2) { create(:account) }
      let!(:installation1) { create(:ai_workflow_template_installation, account: account1) }
      let!(:installation2) { create(:ai_workflow_template_installation, account: account2) }

      it 'filters installations by account' do
        expect(described_class.for_account(account1.id)).to include(installation1)
        expect(described_class.for_account(account1.id)).not_to include(installation2)
      end
    end

    describe '.auto_updating' do
      let!(:auto_update_installation) { create(:ai_workflow_template_installation, auto_update: true) }
      let!(:manual_installation) { create(:ai_workflow_template_installation, auto_update: false) }

      it 'returns only installations with auto_update enabled' do
        expect(described_class.auto_updating).to include(auto_update_installation)
        expect(described_class.auto_updating).not_to include(manual_installation)
      end
    end

    describe '.customized' do
      let!(:customized_installation) { create(:ai_workflow_template_installation, customizations: { key: 'value' }) }
      let!(:default_installation) { create(:ai_workflow_template_installation, customizations: {}) }

      it 'returns only installations with customizations' do
        expect(described_class.customized).to include(customized_installation)
        expect(described_class.customized).not_to include(default_installation)
      end
    end
  end

  describe 'callbacks' do
    describe 'before_validation' do
      it 'generates installation_id if not present' do
        installation = build(:ai_workflow_template_installation, installation_id: nil)
        installation.valid?

        expect(installation.installation_id).to be_present
      end

      it 'captures template_version if not present' do
        template = create(:ai_workflow_template, version: '2.0.0')
        installation = build(:ai_workflow_template_installation,
                            template: template,
                            template_version: nil)
        installation.valid?

        expect(installation.template_version).to eq('2.0.0')
      end
    end
  end

  describe 'instance methods' do
    let(:installation) { create(:ai_workflow_template_installation) }

    describe '#up_to_date?' do
      it 'returns true when template_version matches current template version' do
        installation.template.update!(version: installation.template_version)
        expect(installation.up_to_date?).to be true
      end

      it 'returns false when versions differ' do
        installation.template.update!(version: '2.0.0')
        installation.update!(template_version: '1.0.0')
        expect(installation.up_to_date?).to be false
      end
    end

    describe '#outdated?' do
      it 'returns the opposite of up_to_date?' do
        installation.template.update!(version: '2.0.0')
        installation.update!(template_version: '1.0.0')
        expect(installation.outdated?).to be true
      end
    end

    describe '#customized?' do
      it 'returns true when customizations are present' do
        installation.update!(customizations: { key: 'value' })
        expect(installation.customized?).to be true
      end

      it 'returns false when customizations are empty' do
        installation.update!(customizations: {})
        expect(installation.customized?).to be false
      end
    end

    describe '#has_variable_mappings?' do
      it 'returns true when variable_mappings are present' do
        installation.update!(variable_mappings: { template_var: 'workflow_var' })
        expect(installation.has_variable_mappings?).to be true
      end

      it 'returns false when variable_mappings are empty' do
        installation.update!(variable_mappings: {})
        expect(installation.has_variable_mappings?).to be false
      end
    end

    describe '#template_name' do
      it 'returns the associated template name' do
        expect(installation.template_name).to eq(installation.template.name)
      end
    end

    describe '#workflow_name' do
      it 'returns the associated workflow name' do
        expect(installation.workflow_name).to eq(installation.workflow.name)
      end
    end

    describe '#current_template_version' do
      it 'returns the template current version' do
        installation.template.update!(version: '3.0.0')
        expect(installation.current_template_version).to eq('3.0.0')
      end
    end

    describe '#add_customization' do
      it 'adds a customization key-value pair' do
        installation.add_customization('setting', 'value')
        expect(installation.reload.customizations['setting']).to eq('value')
      end

      it 'updates metadata with customization timestamp' do
        installation.add_customization('setting', 'value')
        expect(installation.reload.metadata['last_customized_at']).to be_present
      end
    end

    describe '#remove_customization' do
      it 'removes a customization key' do
        installation.update!(customizations: { setting1: 'value1', setting2: 'value2' })
        installation.remove_customization('setting1')
        expect(installation.reload.customizations).not_to have_key('setting1')
        expect(installation.customizations['setting2']).to eq('value2')
      end
    end

    describe '#map_variable' do
      it 'adds a variable mapping' do
        installation.map_variable('template_var', 'workflow_var')
        expect(installation.reload.variable_mappings['template_var']).to eq('workflow_var')
      end
    end

    describe '#unmap_variable' do
      it 'removes a variable mapping' do
        installation.update!(variable_mappings: { var1: 'mapped1', var2: 'mapped2' })
        installation.unmap_variable('var1')
        expect(installation.reload.variable_mappings).not_to have_key('var1')
      end
    end

    describe '#resolve_variable' do
      it 'returns mapped variable name when mapping exists' do
        installation.update!(variable_mappings: { 'template_var' => 'workflow_var' })
        expect(installation.resolve_variable('template_var')).to eq('workflow_var')
      end

      it 'returns original variable name when no mapping exists' do
        expect(installation.resolve_variable('unmapped_var')).to eq('unmapped_var')
      end
    end

    describe '#usage_statistics' do
      it 'returns workflow execution statistics' do
        stats = installation.usage_statistics
        expect(stats).to include(
          :total_executions,
          :successful_executions,
          :failed_executions,
          :total_cost,
          :average_execution_time,
          :success_rate
        )
      end
    end

    describe '#installation_health_score' do
      it 'returns a numeric score' do
        expect(installation.installation_health_score).to be_a(Numeric)
        expect(installation.installation_health_score).to be_between(0, 100)
      end
    end

    describe '#installation_summary' do
      it 'returns comprehensive installation information' do
        summary = installation.installation_summary
        expect(summary).to include(
          :installation_id,
          :template_name,
          :workflow_name,
          :installed_version,
          :current_version,
          :up_to_date,
          :customized
        )
      end
    end
  end

  describe 'update management' do
    let(:installation) { create(:ai_workflow_template_installation, template_version: '1.0.0') }

    describe '#can_update?' do
      it 'returns true when outdated and template is published' do
        installation.template.update!(version: '2.0.0', published_at: Time.current)
        expect(installation.can_update?).to be true
      end

      it 'returns false when up to date' do
        installation.template.update!(version: '1.0.0')
        expect(installation.can_update?).to be false
      end

      it 'returns false when template is not published' do
        installation.template.update!(version: '2.0.0', published_at: nil)
        expect(installation.can_update?).to be false
      end
    end
  end

  describe 'performance and edge cases' do
    describe 'unicode and special character handling' do
      it 'handles unicode in customization data' do
        unicode_installation = create(:ai_workflow_template_installation,
                                     customizations: {
                                       workflow_name: 'AI Workflow',
                                       variables: {
                                         title: 'Test with special chars'
                                       }
                                     })

        expect(unicode_installation).to be_valid
        expect(unicode_installation.reload.customizations['workflow_name']).to eq('AI Workflow')
      end
    end
  end
end
