# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Ai::WorkflowRun, type: :model do
  subject(:workflow_run) { build(:ai_workflow_run) }

  describe 'associations' do
    it { is_expected.to belong_to(:workflow) }
    it { is_expected.to belong_to(:account) }
    it { is_expected.to belong_to(:triggered_by_user).class_name('User').optional }
    it { is_expected.to belong_to(:trigger).optional }
    it { is_expected.to have_many(:node_executions).dependent(:destroy) }
    it { is_expected.to have_many(:run_logs).dependent(:destroy) }
    it { is_expected.to have_many(:checkpoints).dependent(:destroy) }
    it { is_expected.to have_many(:a2a_tasks).dependent(:destroy) }
  end

  describe 'validations' do
    # run_id is auto-generated by before_validation callback
    it 'auto-generates run_id if not provided' do
      run = build(:ai_workflow_run, run_id: nil)
      run.valid?
      expect(run.run_id).to be_present
    end

    it { is_expected.to validate_presence_of(:status) }
    it { is_expected.to validate_presence_of(:trigger_type) }

    it { is_expected.to validate_inclusion_of(:status).in_array(%w[initializing running completed failed cancelled waiting_approval]).with_message('must be a valid run status') }
    it { is_expected.to validate_inclusion_of(:trigger_type).in_array(%w[manual webhook schedule event api_call]).with_message('must be a valid trigger type') }

    # Note: Integer and decimal columns auto-cast invalid values before validation,
    # so we verify the model has the validations defined by checking valid values pass
    it 'allows total_nodes, completed_nodes, and failed_nodes with valid values' do
      run = build(:ai_workflow_run, total_nodes: 5, completed_nodes: 2, failed_nodes: 1)
      # The run should pass these specific validations (may fail others)
      run.valid?
      expect(run.errors[:total_nodes]).to be_empty
      expect(run.errors[:completed_nodes]).to be_empty
      expect(run.errors[:failed_nodes]).to be_empty
    end

    it 'allows total_cost with valid values' do
      run = build(:ai_workflow_run, total_cost: 1.50)
      run.valid?
      expect(run.errors[:total_cost]).to be_empty
    end

    context 'execution time validations' do
      it 'validates that completed_at is after started_at when both are present' do
        run = build(:ai_workflow_run,
                   started_at: 1.hour.ago,
                   completed_at: 2.hours.ago)

        expect(run).not_to be_valid
        expect(run.errors[:completed_at]).to include('must be after started_at')
      end

      it 'allows completed_at to be nil' do
        run = build(:ai_workflow_run,
                   started_at: 1.hour.ago,
                   completed_at: nil)

        expect(run).to be_valid
      end
    end

    context 'status-dependent validations' do
      it 'requires completed_at for completed status' do
        workflow = create(:ai_workflow)
        # Build the model directly, bypassing factory after(:build) callback
        run = Ai::WorkflowRun.new(
          workflow: workflow,
          account: workflow.account,
          run_id: SecureRandom.uuid,
          status: 'completed',
          trigger_type: 'manual',
          started_at: 1.hour.ago,
          completed_at: nil
        )

        expect(run).not_to be_valid
        expect(run.errors[:completed_at]).to include("can't be blank for completed runs")
      end

      it 'requires completed_at for failed status' do
        workflow = create(:ai_workflow)
        # Build the model directly, bypassing factory after(:build) callback
        run = Ai::WorkflowRun.new(
          workflow: workflow,
          account: workflow.account,
          run_id: SecureRandom.uuid,
          status: 'failed',
          trigger_type: 'manual',
          started_at: 1.hour.ago,
          completed_at: nil,
          error_details: { 'error_message' => 'test error' }
        )

        expect(run).not_to be_valid
        expect(run.errors[:completed_at]).to include("can't be blank for failed runs")
      end

      it 'requires error_details for failed status' do
        workflow = create(:ai_workflow)
        # Build the model directly, bypassing factory after(:build) callback
        run = Ai::WorkflowRun.new(
          workflow: workflow,
          account: workflow.account,
          run_id: SecureRandom.uuid,
          status: 'failed',
          trigger_type: 'manual',
          started_at: 1.hour.ago,
          completed_at: Time.current,
          error_details: {}
        )

        expect(run).not_to be_valid
        expect(run.errors[:error_details]).to include("can't be blank for failed runs")
      end
    end

    context 'node progress consistency' do
      it 'validates that sum of completed and failed nodes does not exceed total' do
        # Create a valid run first, then use update_columns to set invalid values
        # to bypass callbacks, then validate manually
        run = create(:ai_workflow_run)
        run.assign_attributes(total_nodes: 5, completed_nodes: 4, failed_nodes: 3)

        expect(run).not_to be_valid
        expect(run.errors[:base]).to include('Sum of completed and failed nodes cannot exceed total nodes')
      end
    end
  end

  describe 'scopes' do
    let!(:initializing_run) { create(:ai_workflow_run, status: 'initializing') }
    let!(:running_run) { create(:ai_workflow_run, :running) }
    let!(:completed_run) { create(:ai_workflow_run, :completed) }
    let!(:failed_run) { create(:ai_workflow_run, :failed) }

    describe '.by_status' do
      it 'filters runs by status' do
        expect(described_class.by_status('running')).to include(running_run)
        expect(described_class.by_status('running')).not_to include(initializing_run)
      end
    end

    describe '.active' do
      it 'returns initializing, running and waiting_approval runs' do
        active_runs = described_class.active
        expect(active_runs).to include(initializing_run, running_run)
        expect(active_runs).not_to include(completed_run, failed_run)
      end
    end

    describe '.completed' do
      it 'returns completed runs' do
        expect(described_class.completed).to include(completed_run)
        expect(described_class.completed).not_to include(running_run)
      end
    end

    describe '.failed' do
      it 'returns failed runs' do
        expect(described_class.failed).to include(failed_run)
        expect(described_class.failed).not_to include(completed_run)
      end
    end

    describe '.finished' do
      it 'returns completed, failed and cancelled runs' do
        finished_runs = described_class.finished
        expect(finished_runs).to include(completed_run, failed_run)
        expect(finished_runs).not_to include(running_run)
      end
    end

    describe '.recent' do
      it 'orders runs by created_at descending' do
        old_run = create(:ai_workflow_run, created_at: 1.day.ago)
        new_run = create(:ai_workflow_run, created_at: 1.hour.ago)

        recent = described_class.recent.limit(10)
        expect(recent.to_a.index(new_run)).to be < recent.to_a.index(old_run)
      end
    end

    describe '.by_trigger_type' do
      let!(:manual_run) { create(:ai_workflow_run, trigger_type: 'manual') }
      let!(:scheduled_run) { create(:ai_workflow_run, trigger_type: 'schedule') }

      it 'filters runs by trigger type' do
        expect(described_class.by_trigger_type('manual')).to include(manual_run)
        expect(described_class.by_trigger_type('manual')).not_to include(scheduled_run)
      end
    end

    describe '.for_workflow' do
      let(:workflow1) { create(:ai_workflow) }
      let(:workflow2) { create(:ai_workflow) }
      let!(:run1) { create(:ai_workflow_run, workflow: workflow1) }
      let!(:run2) { create(:ai_workflow_run, workflow: workflow2) }

      it 'filters runs by workflow' do
        expect(described_class.for_workflow(workflow1.id)).to include(run1)
        expect(described_class.for_workflow(workflow1.id)).not_to include(run2)
      end
    end

    describe '.stale' do
      it 'returns runs stuck in active state for more than 30 minutes' do
        stale_run = create(:ai_workflow_run, status: 'running', created_at: 35.minutes.ago)
        fresh_run = create(:ai_workflow_run, status: 'running', created_at: 10.minutes.ago)

        expect(described_class.stale).to include(stale_run)
        expect(described_class.stale).not_to include(fresh_run)
      end
    end
  end

  describe 'state machine and callbacks' do
    describe 'status transitions' do
      it 'starts in initializing status' do
        run = create(:ai_workflow_run)
        expect(run.status).to eq('initializing')
      end

      it 'can transition from initializing to running via start_execution!' do
        run = create(:ai_workflow_run, status: 'initializing')
        run.start_execution!
        expect(run.status).to eq('running')
        expect(run.started_at).to be_present
      end

      it 'can transition from running to completed via complete_execution!' do
        run = create(:ai_workflow_run, :running)
        run.complete_execution!({ result: 'success' })
        expect(run.status).to eq('completed')
        expect(run.completed_at).to be_present
      end

      it 'can transition from running to failed via fail_execution!' do
        run = create(:ai_workflow_run, :running)
        run.fail_execution!('Execution error occurred')
        expect(run.status).to eq('failed')
        expect(run.completed_at).to be_present
        expect(run.error_details['error_message']).to eq('Execution error occurred')
      end

      it 'can pause for approval and resume execution' do
        run = create(:ai_workflow_run, :running)
        run.pause_for_approval!('node_123', 'Human approval required')
        expect(run.status).to eq('waiting_approval')

        run.resume_after_approval!(create(:user).id, 'approved')
        expect(run.status).to eq('running')
      end

      it 'can cancel execution' do
        run = create(:ai_workflow_run, :running)
        run.cancel_execution!
        expect(run.status).to eq('cancelled')
        expect(run.completed_at).to be_present
      end
    end

    describe 'callbacks' do
      describe 'before_create' do
        it 'generates run_id if not present' do
          run = build(:ai_workflow_run, run_id: nil)
          run.save!
          expect(run.run_id).to be_present
        end

        it 'preserves provided run_id' do
          custom_uuid = SecureRandom.uuid
          run = build(:ai_workflow_run, run_id: custom_uuid)
          run.save!
          expect(run.run_id).to eq(custom_uuid)
        end

        it 'sets initial node counts to 0' do
          run = create(:ai_workflow_run)
          expect(run.completed_nodes).to eq(0)
          expect(run.failed_nodes).to eq(0)
        end
      end
    end
  end

  describe 'status check methods' do
    describe '#initializing?' do
      it 'returns true for initializing status' do
        run = build(:ai_workflow_run, status: 'initializing')
        expect(run.initializing?).to be true
      end
    end

    describe '#running?' do
      it 'returns true for running status' do
        run = build(:ai_workflow_run, status: 'running')
        expect(run.running?).to be true
      end
    end

    describe '#completed?' do
      it 'returns true for completed status' do
        run = build(:ai_workflow_run, status: 'completed')
        expect(run.completed?).to be true
      end
    end

    describe '#failed?' do
      it 'returns true for failed status' do
        run = build(:ai_workflow_run, status: 'failed')
        expect(run.failed?).to be true
      end

      it 'returns false for other statuses' do
        run = build(:ai_workflow_run, status: 'completed')
        expect(run.failed?).to be false
      end
    end

    describe '#cancelled?' do
      it 'returns true for cancelled status' do
        run = build(:ai_workflow_run, status: 'cancelled')
        expect(run.cancelled?).to be true
      end
    end

    describe '#waiting_for_approval?' do
      it 'returns true for waiting_approval status' do
        run = build(:ai_workflow_run, status: 'waiting_approval')
        expect(run.waiting_for_approval?).to be true
      end
    end

    describe '#active?' do
      it 'returns true for initializing status' do
        run = build(:ai_workflow_run, status: 'initializing')
        expect(run.active?).to be true
      end

      it 'returns true for running status' do
        run = build(:ai_workflow_run, status: 'running')
        expect(run.active?).to be true
      end

      it 'returns true for waiting_approval status' do
        run = build(:ai_workflow_run, status: 'waiting_approval')
        expect(run.active?).to be true
      end

      it 'returns false for completed status' do
        run = build(:ai_workflow_run, status: 'completed')
        expect(run.active?).to be false
      end
    end

    describe '#finished?' do
      it 'returns true for completed status' do
        run = build(:ai_workflow_run, status: 'completed')
        expect(run.finished?).to be true
      end

      it 'returns true for failed status' do
        run = build(:ai_workflow_run, status: 'failed')
        expect(run.finished?).to be true
      end

      it 'returns true for cancelled status' do
        run = build(:ai_workflow_run, status: 'cancelled')
        expect(run.finished?).to be true
      end

      it 'returns false for running status' do
        run = build(:ai_workflow_run, status: 'running')
        expect(run.finished?).to be false
      end
    end

    describe '#successful?' do
      it 'returns true for completed status with no failed nodes' do
        run = build(:ai_workflow_run, status: 'completed', failed_nodes: 0)
        expect(run.successful?).to be true
      end

      it 'returns false for completed status with failed nodes' do
        run = build(:ai_workflow_run, status: 'completed', failed_nodes: 1, total_nodes: 5, completed_nodes: 4)
        expect(run.successful?).to be false
      end
    end
  end

  describe 'instance methods' do
    describe '#execution_duration' do
      it 'returns nil when not started' do
        run = create(:ai_workflow_run, started_at: nil)
        expect(run.execution_duration).to be_nil
      end

      it 'returns duration from start to completion' do
        started = 1.hour.ago
        completed = 30.minutes.ago
        run = create(:ai_workflow_run, :completed, started_at: started, completed_at: completed)
        expect(run.execution_duration).to be_within(1).of(30.minutes.to_i)
      end

      it 'returns duration from start to now for running workflows' do
        run = create(:ai_workflow_run, :running, started_at: 1.hour.ago)
        expect(run.execution_duration).to be_within(5).of(1.hour.to_i)
      end
    end

    describe '#progress_percentage' do
      it 'returns 0 when total_nodes is 0' do
        run = build(:ai_workflow_run, total_nodes: 0, completed_nodes: 0)
        expect(run.progress_percentage).to eq(0)
      end

      it 'returns 100 when completed' do
        run = build(:ai_workflow_run, status: 'completed', total_nodes: 5, completed_nodes: 5)
        expect(run.progress_percentage).to eq(100)
      end

      it 'calculates percentage based on completed nodes' do
        run = build(:ai_workflow_run, total_nodes: 10, completed_nodes: 3)
        expect(run.progress_percentage).to eq(30.0)
      end
    end

    describe '#execution_progress' do
      it 'returns progress summary hash' do
        run = build(:ai_workflow_run,
                   status: 'running',
                   total_nodes: 10,
                   completed_nodes: 3,
                   failed_nodes: 1)

        progress = run.execution_progress

        expect(progress[:percentage]).to eq(30.0)
        expect(progress[:completed_nodes]).to eq(3)
        expect(progress[:failed_nodes]).to eq(1)
        expect(progress[:pending_nodes]).to eq(6)
        expect(progress[:total_nodes]).to eq(10)
        expect(progress[:current_status]).to eq('running')
      end
    end

    describe '#can_cancel?' do
      it 'returns true for active runs' do
        run = build(:ai_workflow_run, status: 'running')
        expect(run.can_cancel?).to be true
      end

      it 'returns false for completed runs' do
        run = build(:ai_workflow_run, status: 'completed')
        expect(run.can_cancel?).to be false
      end
    end

    describe '#can_retry?' do
      it 'returns true for failed runs when workflow can execute' do
        workflow = create(:ai_workflow)
        allow(workflow).to receive(:can_execute?).and_return(true)
        run = create(:ai_workflow_run, :failed, workflow: workflow)

        expect(run.can_retry?).to be true
      end

      it 'returns false for completed runs' do
        run = build(:ai_workflow_run, status: 'completed')
        expect(run.can_retry?).to be false
      end
    end

    describe '#execution_summary' do
      let(:run) { create(:ai_workflow_run, :completed) }

      it 'returns comprehensive execution summary' do
        summary = run.execution_summary

        expect(summary).to include(
          :run_id,
          :workflow_name,
          :status,
          :trigger_type,
          :progress,
          :cost,
          :timestamps,
          :node_summary
        )

        expect(summary[:status]).to eq('completed')
      end
    end

    describe '#get_variable' do
      it 'retrieves variable from runtime_context' do
        run = build(:ai_workflow_run,
                   runtime_context: { 'variables' => { 'test_var' => 'test_value' } })

        expect(run.get_variable('test_var')).to eq('test_value')
      end

      it 'falls back to input_variables' do
        run = build(:ai_workflow_run,
                   input_variables: { 'input_var' => 'input_value' },
                   runtime_context: {})

        expect(run.get_variable('input_var')).to eq('input_value')
      end
    end

    describe '#set_variable' do
      it 'sets variable in runtime_context' do
        run = create(:ai_workflow_run)
        run.set_variable('new_var', 'new_value')

        expect(run.reload.runtime_context.dig('variables', 'new_var')).to eq('new_value')
      end
    end

    describe '#cost_breakdown' do
      it 'returns cost summary' do
        run = create(:ai_workflow_run)
        run.update_column(:total_cost, 1.5)  # Bypass callback resetting cost

        breakdown = run.cost_breakdown
        expect(breakdown[:total_cost]).to eq(1.5)
        expect(breakdown).to have_key(:node_costs)
        expect(breakdown).to have_key(:cost_per_node)
      end
    end
  end

  describe 'performance and edge cases' do
    describe 'large input/output data handling' do
      it 'handles large input variables' do
        large_input = { 'data' => Array.new(1000) { |i| { "item_#{i}" => "value_#{i}" } } }
        run = create(:ai_workflow_run, input_variables: large_input)

        expect(run.input_variables['data'].size).to eq(1000)
        expect(run.reload.input_variables).to eq(large_input)
      end

      it 'handles large output variables' do
        large_output = { 'results' => Array.new(1000) { |i| "result_#{i}" } }
        run = create(:ai_workflow_run, :running)
        run.complete_execution!(large_output)

        expect(run.output_variables['results'].size).to eq(1000)
      end
    end

    describe 'unicode and special character support' do
      it 'handles unicode in error messages' do
        run = create(:ai_workflow_run, :running)
        unicode_error = 'Error message with unicode'

        run.fail_execution!(unicode_error)
        expect(run.error_details['error_message']).to eq(unicode_error)
        expect(run.reload.error_details['error_message']).to eq(unicode_error)
      end

      it 'handles special characters in trigger context' do
        context = {
          'webhook_data' => {
            'message' => 'Special chars: @#$%^&*()[]{}|;:,.<>?'
          }
        }

        run = create(:ai_workflow_run, metadata: { 'trigger_context' => context })
        expect(run.trigger_context['webhook_data']['message']).to include('@#$%^&')
      end
    end

    describe 'concurrent run management' do
      let!(:workflow) { create(:ai_workflow) }

      it 'handles multiple concurrent runs' do
        runs = 5.times.map do
          create(:ai_workflow_run, workflow: workflow)
        end

        run_ids = runs.map(&:run_id)
        expect(run_ids.uniq.size).to eq(5)
        expect(runs.all?(&:persisted?)).to be true
      end
    end
  end
end
