/**
 * Test Credentials Utility
 *
 * Provides access to test user credentials that are generated by the seeding process.
 * Credentials are stored in the project root as test-credentials.json (gitignored).
 *
 * Usage in tests:
 *   import { testCredentials } from '@/test-utils/testCredentials';
 *
 *   testCredentials.demo.email      // => "demo@powernode.org"
 *   testCredentials.demo.password   // => "randomly_generated_password"
 *   testCredentials.admin           // => { email: "...", password: "..." }
 *
 * To regenerate credentials, run: cd server && rails db:seed
 */

import * as fs from 'fs';
import * as path from 'path';

interface UserCredentials {
  email: string;
  password: string;
}

interface TestCredentialsData {
  demo?: UserCredentials;
  admin?: UserCredentials;
  manager?: UserCredentials;
  billing?: UserCredentials;
  member?: UserCredentials;
}

class TestCredentialsLoader {
  private credentials: TestCredentialsData | null = null;
  private loaded = false;

  private loadCredentials(): TestCredentialsData {
    if (this.loaded) {
      return this.credentials || {};
    }

    this.loaded = true;

    // Load from project root (test-credentials.json)
    // __dirname is frontend/src/test-utils, project root is 3 levels up
    const credentialsPath = path.join(
      __dirname,
      '../../../test-credentials.json'
    );

    try {
      if (fs.existsSync(credentialsPath)) {
        const content = fs.readFileSync(credentialsPath, 'utf-8');
        this.credentials = JSON.parse(content);
        return this.credentials || {};
      }
    } catch {
      console.warn('⚠️ Failed to load test credentials:', error);
    }

    console.warn(
      '⚠️ Test credentials file not found. Run "cd server && rails db:seed" to generate.'
    );
    return {};
  }

  get demo(): UserCredentials {
    const creds = this.loadCredentials();
    return creds.demo || {
      email: 'demo@powernode.org',
      password: 'CREDENTIALS_NOT_LOADED',
    };
  }

  get admin(): UserCredentials {
    const creds = this.loadCredentials();
    return creds.admin || {
      email: 'admin@powernode.org',
      password: 'CREDENTIALS_NOT_LOADED',
    };
  }

  get manager(): UserCredentials {
    const creds = this.loadCredentials();
    return creds.manager || {
      email: 'manager@powernode.org',
      password: 'CREDENTIALS_NOT_LOADED',
    };
  }

  get billing(): UserCredentials {
    const creds = this.loadCredentials();
    return creds.billing || {
      email: 'billing@powernode.org',
      password: 'CREDENTIALS_NOT_LOADED',
    };
  }

  get member(): UserCredentials {
    const creds = this.loadCredentials();
    return creds.member || {
      email: 'member@powernode.org',
      password: 'CREDENTIALS_NOT_LOADED',
    };
  }

  /**
   * Get credentials for a specific role
   */
  forRole(role: 'demo' | 'admin' | 'manager' | 'billing' | 'member'): UserCredentials {
    switch (role) {
      case 'demo':
        return this.demo;
      case 'admin':
        return this.admin;
      case 'manager':
        return this.manager;
      case 'billing':
        return this.billing;
      case 'member':
        return this.member;
      default:
        throw new Error(`Unknown role: ${role}`);
    }
  }

  /**
   * Check if credentials are available
   */
  get available(): boolean {
    const creds = this.loadCredentials();
    return Boolean(creds.demo?.email && creds.demo?.password);
  }

  /**
   * Reload credentials from file
   */
  reload(): void {
    this.loaded = false;
    this.credentials = null;
    this.loadCredentials();
  }
}

export const testCredentials = new TestCredentialsLoader();

// Export types
export type { UserCredentials, TestCredentialsData };
