#!/bin/bash

# Reverse Proxy Configuration Setup Script
# This script configures the reverse proxy settings for Powernode platform
# Based on current configuration for dev-1.ipnode.net

set -e

SCRIPT_DIR=$(dirname "$0")
PROJECT_ROOT=$(realpath "$SCRIPT_DIR/..")
FRONTEND_DIR="$PROJECT_ROOT/frontend"
SERVER_DIR="$PROJECT_ROOT/server"

echo "🔧 Powernode Reverse Proxy Configuration Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Configuration variables
PROXY_HOST="${PROXY_HOST:-dev-1.ipnode.net}"
PROXY_PROTOCOL="${PROXY_PROTOCOL:-https}"
BACKEND_PORT="${BACKEND_PORT:-3000}"
FRONTEND_PORT="${FRONTEND_PORT:-3001}"
SETUP_TYPE="${1:-external}"  # external or local

# Function to create frontend environment configuration
setup_frontend_env() {
    echo "📝 Setting up frontend environment configuration..."
    
    cat > "$FRONTEND_DIR/.env.local" << EOF
# Reverse Proxy Configuration
# Generated by setup-reverse-proxy.sh on $(date)

# Application Version
VITE_APP_VERSION=0.0.2

# External Proxy URLs
VITE_API_BASE_URL=${PROXY_PROTOCOL}://${PROXY_HOST}/api/v1
VITE_WS_BASE_URL=${PROXY_PROTOCOL/https/wss}${PROXY_PROTOCOL/http/ws}://${PROXY_HOST}/cable

# Reverse Proxy Settings
VITE_BEHIND_PROXY=true
VITE_PROXY_HOST=${PROXY_HOST}
VITE_PROXY_PROTOCOL=${PROXY_PROTOCOL}
VITE_AUTO_DETECT_BACKEND=false

# Allowed Hosts (automatically fetched from backend)
# Additional hosts can be added here if needed
# VITE_ALLOWED_HOSTS=dev-1.ipnode.net,.ipnode.net

# Server Configuration
HOST=0.0.0.0
PORT=${FRONTEND_PORT}
EOF
    
    echo "✅ Created $FRONTEND_DIR/.env.local"
}

# Function to create Vite external proxy configuration
setup_vite_external_config() {
    echo "📝 Creating Vite external proxy configuration..."
    
    # Check if external config already exists, if not create from template
    if [ ! -f "$FRONTEND_DIR/vite.config.external-proxy.ts" ]; then
        echo "   Creating vite.config.external-proxy.ts..."
        # Config is already created in the codebase
        echo "   ✓ Using existing external proxy configuration"
    else
        echo "   ✓ External proxy configuration already exists"
    fi
}

# Function to setup nginx configuration
setup_nginx_config() {
    echo "📝 Generating nginx configuration..."
    
    cat > "$PROJECT_ROOT/nginx-proxy.conf" << EOF
# Nginx Reverse Proxy Configuration for Powernode
# Generated by setup-reverse-proxy.sh on $(date)

upstream frontend {
    server localhost:${FRONTEND_PORT};
}

upstream backend {
    server localhost:${BACKEND_PORT};
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${PROXY_HOST};

    # SSL configuration (update paths as needed)
    # ssl_certificate /etc/ssl/certs/${PROXY_HOST}.pem;
    # ssl_certificate_key /etc/ssl/private/${PROXY_HOST}.key;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Frontend application
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        
        # Standard proxy headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # WebSocket support for HMR
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Disable buffering
        proxy_buffering off;
        proxy_cache off;
        
        # Ensure Vite client gets correct origin
        proxy_set_header Origin \$scheme://\$host;
    }

    # Vite HMR WebSocket
    location ~ ^/@vite/(client|hmr) {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        
        # WebSocket headers
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Standard headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header Origin \$scheme://\$host;
        
        # Disable buffering for real-time
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        
        # Keep connection alive
        proxy_socket_keepalive on;
    }
    
    # Vite assets
    location /@vite/ {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        
        proxy_buffering off;
        proxy_cache off;
    }

    # Backend API
    location /api/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        
        # Standard headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Port \$server_port;
        
        # API specific settings
        client_max_body_size 10M;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Rails ActionCable WebSocket
    location /cable {
        proxy_pass http://backend/cable;
        proxy_http_version 1.1;
        
        # WebSocket headers
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Standard headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # Keep alive for WebSocket
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Redirect HTTP to HTTPS
    error_page 497 https://\$host\$request_uri;
}

# HTTP redirect server
server {
    listen 80;
    listen [::]:80;
    server_name ${PROXY_HOST};
    return 301 https://\$host\$request_uri;
}
EOF
    
    echo "✅ Created $PROJECT_ROOT/nginx-proxy.conf"
}

# Function to setup backend proxy configuration
setup_backend_proxy() {
    echo "📝 Configuring backend proxy settings..."
    
    # Create proxy settings configuration for Rails
    cat > "$SERVER_DIR/config/proxy_settings.yml" << EOF
# Proxy Settings Configuration
# Generated by setup-reverse-proxy.sh on $(date)

default: &default
  enabled: true
  trusted_hosts:
    - localhost
    - 127.0.0.1
    - ${PROXY_HOST}
    - .ipnode.net
  default_host: ${PROXY_HOST}
  force_ssl: true
  multi_tenancy:
    enabled: true
    wildcard_patterns:
      - "*.ipnode.net"
  security:
    validate_host: true
    validate_forwarded_proto: true
    reject_unmatched_hosts: false
    require_ssl_in_production: true

development:
  <<: *default

test:
  <<: *default
  force_ssl: false

production:
  <<: *default
  security:
    validate_host: true
    validate_forwarded_proto: true
    reject_unmatched_hosts: true
    require_ssl_in_production: true
EOF
    
    echo "✅ Created $SERVER_DIR/config/proxy_settings.yml"
}

# Function to create startup script
create_startup_script() {
    echo "📝 Creating startup script..."
    
    cat > "$PROJECT_ROOT/start-with-proxy.sh" << 'EOF'
#!/bin/bash

# Start Powernode with Reverse Proxy Configuration
set -e

SCRIPT_DIR=$(dirname "$0")
PROJECT_ROOT=$(realpath "$SCRIPT_DIR")

echo "🚀 Starting Powernode with Reverse Proxy Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Function to stop services on exit
cleanup() {
    echo ""
    echo "🛑 Stopping services..."
    kill $(jobs -p) 2>/dev/null || true
    exit 0
}

trap cleanup INT TERM

# Start backend
echo "▶️  Starting Rails backend..."
cd "$PROJECT_ROOT/server"
bundle exec rails server -p 3000 &
BACKEND_PID=$!

# Wait for backend to be ready
echo "⏳ Waiting for backend to start..."
while ! curl -s http://localhost:3000/health > /dev/null 2>&1; do
    sleep 1
done
echo "✅ Backend is running on port 3000"

# Start worker
echo "▶️  Starting Sidekiq worker..."
cd "$PROJECT_ROOT/worker"
bundle exec sidekiq &
WORKER_PID=$!
echo "✅ Worker is running"

# Start frontend with external proxy config
echo "▶️  Starting frontend with proxy configuration..."
cd "$PROJECT_ROOT/frontend"
npx vite --config vite.config.external-proxy.ts --host 0.0.0.0 &
FRONTEND_PID=$!

# Wait for frontend to be ready
echo "⏳ Waiting for frontend to start..."
while ! curl -s http://localhost:3001 > /dev/null 2>&1; do
    sleep 1
done
echo "✅ Frontend is running on port 3001"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Powernode is running with reverse proxy configuration!"
echo ""
echo "📍 Local Access:"
echo "   Frontend: http://localhost:3001"
echo "   Backend:  http://localhost:3000"
echo ""
echo "🌐 Proxy Access (requires nginx):"
EOF
    
    echo "   Frontend: ${PROXY_PROTOCOL}://${PROXY_HOST}" >> "$PROJECT_ROOT/start-with-proxy.sh"
    echo "   Backend:  ${PROXY_PROTOCOL}://${PROXY_HOST}/api/v1" >> "$PROJECT_ROOT/start-with-proxy.sh"
    
    cat >> "$PROJECT_ROOT/start-with-proxy.sh" << 'EOF'
echo ""
echo "Press Ctrl+C to stop all services"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Wait for all background processes
wait $BACKEND_PID $WORKER_PID $FRONTEND_PID
EOF
    
    chmod +x "$PROJECT_ROOT/start-with-proxy.sh"
    echo "✅ Created $PROJECT_ROOT/start-with-proxy.sh"
}

# Function to display configuration summary
display_summary() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ Reverse Proxy Configuration Complete!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📋 Configuration Summary:"
    echo "   Proxy Host:     ${PROXY_HOST}"
    echo "   Protocol:       ${PROXY_PROTOCOL}"
    echo "   Frontend Port:  ${FRONTEND_PORT}"
    echo "   Backend Port:   ${BACKEND_PORT}"
    echo ""
    echo "📁 Generated Files:"
    echo "   • $FRONTEND_DIR/.env.local"
    echo "   • $PROJECT_ROOT/nginx-proxy.conf"
    echo "   • $SERVER_DIR/config/proxy_settings.yml"
    echo "   • $PROJECT_ROOT/start-with-proxy.sh"
    echo ""
    echo "🚀 Next Steps:"
    echo ""
    echo "1. Start the application with proxy support:"
    echo "   ./start-with-proxy.sh"
    echo ""
    echo "2. Configure nginx (if using external proxy):"
    echo "   sudo cp nginx-proxy.conf /etc/nginx/sites-available/powernode"
    echo "   sudo ln -s /etc/nginx/sites-available/powernode /etc/nginx/sites-enabled/"
    echo "   sudo nginx -t && sudo systemctl reload nginx"
    echo ""
    echo "3. Or use the development scripts:"
    echo "   cd frontend && ./scripts/dev-external-proxy.sh"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# Main execution
main() {
    echo "🔍 Configuration Type: $SETUP_TYPE"
    echo "🌐 Proxy Host: $PROXY_HOST"
    echo "🔒 Protocol: $PROXY_PROTOCOL"
    echo ""
    
    # Create necessary directories
    mkdir -p "$FRONTEND_DIR/scripts"
    mkdir -p "$SERVER_DIR/config"
    
    # Run setup functions
    setup_frontend_env
    setup_vite_external_config
    setup_nginx_config
    setup_backend_proxy
    create_startup_script
    
    # Display summary
    display_summary
}

# Handle command line arguments
case "$1" in
    --help|-h)
        echo "Usage: $0 [external|local] [PROXY_HOST] [PROXY_PROTOCOL]"
        echo ""
        echo "Examples:"
        echo "  $0                    # Use defaults (external, dev-1.ipnode.net, https)"
        echo "  $0 local              # Local development setup"
        echo "  $0 external prod.example.com https"
        echo ""
        echo "Environment variables:"
        echo "  PROXY_HOST     - Proxy hostname (default: dev-1.ipnode.net)"
        echo "  PROXY_PROTOCOL - Protocol to use (default: https)"
        echo "  BACKEND_PORT   - Backend port (default: 3000)"
        echo "  FRONTEND_PORT  - Frontend port (default: 3001)"
        exit 0
        ;;
    local)
        PROXY_HOST="localhost"
        PROXY_PROTOCOL="http"
        ;;
    external)
        # Use defaults or environment variables
        ;;
    *)
        # Custom configuration
        if [ -n "$2" ]; then
            PROXY_HOST="$2"
        fi
        if [ -n "$3" ]; then
            PROXY_PROTOCOL="$3"
        fi
        ;;
esac

# Run main setup
main