# frozen_string_literal: true

# AI Todo App Team Seed
# Creates 5 agents (mixed providers), 1 hierarchical team, channels, and shared memory pool
# for collaboratively building a Todo/Task application.

puts "\n📋 Seeding AI Todo App Team..."

admin_account = Account.find_by(name: "Powernode Admin")
admin_user = admin_account&.users&.find_by(email: "admin@powernode.org")

unless admin_account && admin_user
  puts "  ⏭️  Admin account/user not found — skipping AI Todo App Team"
  return
end

# ---------------------------------------------------------------------------
# Resolve Providers
# ---------------------------------------------------------------------------
anthropic_provider = Ai::Provider.find_by(provider_type: 'anthropic')
openai_provider    = Ai::Provider.find_by(provider_type: 'openai')
grok_provider      = Ai::Provider.find_by(name: 'Grok (X.AI)') ||
                     Ai::Provider.where(provider_type: 'custom').where("name ILIKE ?", "%grok%").first

unless anthropic_provider
  puts "  ⚠️  Anthropic provider not found — skipping AI Todo App Team"
  return
end

unless openai_provider
  puts "  ⚠️  OpenAI provider not found — skipping AI Todo App Team"
  return
end

unless grok_provider
  puts "  ⚠️  Grok (X.AI) provider not found — skipping AI Todo App Team"
  return
end

puts "  ✅ Providers: Anthropic=#{anthropic_provider.id}, OpenAI=#{openai_provider.id}, Grok=#{grok_provider.id}"

# ---------------------------------------------------------------------------
# Agent Definitions
# ---------------------------------------------------------------------------
# NOTE: mcp_tool_manifest is auto-generated by the ensure_mcp_tool_manifest callback.
# Custom config (system_prompt, model, temperature, max_tokens) goes in mcp_metadata
# following the same pattern as claude_agents_seed.rb.
# ---------------------------------------------------------------------------
agents_data = [
  {
    name: 'Todo Team Lead',
    agent_type: 'code_assistant',
    provider: anthropic_provider,
    description: 'Code review specialist and team coordinator for the Todo App project. Manages architecture decisions, delegates tasks, reviews all PRs, and coordinates team communication.',
    mcp_metadata: {
      'specialization' => 'code_review_team_lead',
      'priority_level' => 'high',
      'execution_mode' => 'analytical',
      'capabilities_version' => '1.0',
      'cost_tier' => 'mid',
      'model_config' => {
        'provider' => 'anthropic',
        'model' => 'claude-sonnet-4-20250514',
        'temperature' => 0.3,
        'max_tokens' => 4096,
        'response_format' => 'code_review',
        'cost_per_1k' => { 'input' => 0.003, 'output' => 0.015 }
      },
      'system_prompt' => <<~PROMPT.strip
        You are the Team Lead and Code Review Specialist for the Todo App project.

        RESPONSIBILITIES:
        - Review all code changes for correctness, security, and maintainability
        - Make architectural decisions and document them in the shared memory
        - Delegate tasks to team members based on their specializations
        - Coordinate parallel development using git worktrees
        - Ask clarifying questions when requirements are ambiguous
        - Manage the todo-broadcast and todo-tasks channels

        WORKFLOW:
        1. Break down features into backend, frontend, test, and devops tasks
        2. Assign tasks via the todo-tasks channel
        3. Review completed work before merging
        4. Update shared memory with decisions and conventions

        CONVENTIONS:
        - Backend: Rails API with render_success/render_error, UUIDv7 PKs
        - Frontend: React TypeScript with theme classes (bg-theme-*, text-theme-*)
        - Tests: RSpec for backend, Jest/RTL for frontend
        - Git: Feature branches off develop, no force pushes
      PROMPT
    }
  },
  {
    name: 'Todo Backend Developer',
    agent_type: 'code_assistant',
    provider: anthropic_provider,
    description: 'Rails API specialist. Builds models, controllers, services, and migrations for the Todo App backend following established conventions.',
    mcp_metadata: {
      'specialization' => 'rails_backend',
      'priority_level' => 'medium',
      'execution_mode' => 'generative',
      'capabilities_version' => '1.0',
      'cost_tier' => 'low',
      'model_config' => {
        'provider' => 'anthropic',
        'model' => 'claude-haiku-4-5-20251001',
        'temperature' => 0.2,
        'max_tokens' => 4096,
        'response_format' => 'code_generation',
        'cost_per_1k' => { 'input' => 0.001, 'output' => 0.005 }
      },
      'system_prompt' => <<~PROMPT.strip
        You are the Backend Developer for the Todo App project.

        RESPONSIBILITIES:
        - Build Rails API endpoints (controllers, models, services)
        - Write database migrations with inline indexes on t.references
        - Implement business logic in service objects
        - Follow render_success/render_error response patterns
        - Add frozen_string_literal pragma to all Ruby files

        STACK:
        - Rails 8 API-only, PostgreSQL, UUIDv7 primary keys
        - JWT authentication, permission-based authorization
        - RESTful routes under Api::V1 namespace

        CONVENTIONS:
        - Controllers inherit from ApplicationController
        - Use render_success(data, status:) and render_error(message, status:)
        - Never create separate indexes for t.references columns
        - Service objects for complex business logic
        - Rails.logger for logging, never puts/print
      PROMPT
    }
  },
  {
    name: 'Todo Frontend Developer',
    agent_type: 'code_assistant',
    provider: grok_provider,
    description: 'React/TypeScript specialist. Builds UI components, pages, and state management for the Todo App frontend using theme-aware Tailwind CSS.',
    mcp_metadata: {
      'specialization' => 'react_frontend',
      'priority_level' => 'medium',
      'execution_mode' => 'generative',
      'capabilities_version' => '1.0',
      'cost_tier' => 'low',
      'model_config' => {
        'provider' => 'xai',
        'model' => 'grok-3-mini-fast',
        'temperature' => 0.3,
        'max_tokens' => 4096,
        'response_format' => 'code_generation',
        'cost_per_1m' => { 'input' => 0.05, 'output' => 0.10 }
      },
      'system_prompt' => <<~PROMPT.strip
        You are the Frontend Developer for the Todo App project.

        RESPONSIBILITIES:
        - Build React components with TypeScript (no 'any' types)
        - Implement UI with Tailwind CSS using theme classes only
        - Use permission-based access control, never role-based
        - Create reusable components with proper prop typing
        - Manage state with React hooks and context

        STACK:
        - React 18+ with TypeScript, Tailwind CSS
        - Path aliases: @/shared/, @/features/
        - Theme classes: bg-theme-*, text-theme-*, border-theme-*

        CONVENTIONS:
        - No hardcoded colors — theme classes only
        - No console.log in production code
        - Actions in PageContainer, not in page content
        - Global notifications only, no local success/error state
        - Flat navigation structure, no submenus
      PROMPT
    }
  },
  {
    name: 'Todo QA Engineer',
    agent_type: 'code_assistant',
    provider: openai_provider,
    description: 'Test specialist. Writes RSpec tests for backend APIs and Jest/React Testing Library tests for frontend components. Validates edge cases and reports bugs.',
    mcp_metadata: {
      'specialization' => 'qa_testing',
      'priority_level' => 'medium',
      'execution_mode' => 'analytical',
      'capabilities_version' => '1.0',
      'cost_tier' => 'minimal',
      'model_config' => {
        'provider' => 'openai',
        'model' => 'gpt-4o-mini',
        'temperature' => 0.1,
        'max_tokens' => 4096,
        'response_format' => 'code_generation',
        'cost_per_1k' => { 'input' => 0.00015, 'output' => 0.0006 }
      },
      'system_prompt' => <<~PROMPT.strip
        You are the QA Engineer for the Todo App project.

        RESPONSIBILITIES:
        - Write RSpec request specs for all API endpoints
        - Write Jest/React Testing Library tests for frontend components
        - Test edge cases: empty states, validation errors, auth failures
        - Report bugs with reproduction steps to the team lead
        - Verify fixes and perform regression testing

        BACKEND TESTING:
        - RSpec with FactoryBot, request specs preferred
        - Test all response codes and error messages
        - Use parallel_rspec for fast execution

        FRONTEND TESTING:
        - Jest with React Testing Library
        - Test user interactions, not implementation details
        - Use CI=true for consistent test runs
        - data-testid attributes for test selectors
      PROMPT
    }
  },
  {
    name: 'Todo DevOps & Docs',
    agent_type: 'code_assistant',
    provider: openai_provider,
    description: 'Handles Gitea repository setup, CI/CD configuration, documentation, and deployment via Docker. Manages project scaffolding and infrastructure.',
    mcp_metadata: {
      'specialization' => 'devops_documentation',
      'priority_level' => 'low',
      'execution_mode' => 'generative',
      'capabilities_version' => '1.0',
      'cost_tier' => 'minimal',
      'model_config' => {
        'provider' => 'openai',
        'model' => 'gpt-4o-mini',
        'temperature' => 0.2,
        'max_tokens' => 4096,
        'response_format' => 'documentation',
        'cost_per_1k' => { 'input' => 0.00015, 'output' => 0.0006 }
      },
      'system_prompt' => <<~PROMPT.strip
        You are the DevOps & Documentation Specialist for the Todo App project.

        RESPONSIBILITIES:
        - Set up and manage the Gitea repository
        - Configure CI/CD pipelines for automated testing and deployment
        - Write and maintain project documentation (README, ARCHITECTURE, API docs)
        - Create Docker/Docker Compose configurations
        - Manage git worktrees for parallel development branches

        TOOLING:
        - Gitea for git hosting and CI/CD
        - Docker and Docker Compose for containerization
        - Markdown for documentation

        CONVENTIONS:
        - Branch strategy: develop -> feature/* -> release/* -> master
        - No "v" prefix on tags (use 0.1.0, not v0.1.0)
        - Keep docs updated with architecture decisions
        - Document all API endpoints with request/response examples
      PROMPT
    }
  }
]

# ---------------------------------------------------------------------------
# Create Agents
# ---------------------------------------------------------------------------
agents = {}
agents_created = 0

agents_data.each do |ad|
  agent = Ai::Agent.find_or_create_by(account: admin_account, name: ad[:name]) do |a|
    a.description = ad[:description]
    a.agent_type = ad[:agent_type]
    a.provider = ad[:provider]
    a.creator = admin_user
    a.status = 'active'
    a.version = '1.0.0'
    a.mcp_metadata = ad[:mcp_metadata]
  end
  agents[ad[:name]] = agent
  agents_created += 1
  model = ad[:mcp_metadata].dig('model_config', 'model')
  puts "  ✅ Agent '#{agent.name}' (#{ad[:provider].name} / #{model})"
end

# ---------------------------------------------------------------------------
# Team Definition
# ---------------------------------------------------------------------------
team = Ai::AgentTeam.find_or_create_by!(account: admin_account, name: 'Todo App Development Team') do |t|
  t.description = 'Hierarchical multi-provider team for building a full-stack Todo/Task application. Led by a code review specialist with mixed-provider cost-optimized model assignments.'
  t.team_type = 'hierarchical'
  t.coordination_strategy = 'manager_led'
  t.goal_description = 'Build a full-stack Todo/Task application with REST API backend, React frontend, tests, and deployment configuration'
  t.team_config = {
    'max_iterations' => 10,
    'timeout_seconds' => 1800,
    'retry_on_failure' => true,
    'max_retries' => 2
  }
  t.review_config = {
    'development' => { 'mode' => 'shadow', 'require_approval' => false }
  }
  t.status = 'active'
end

puts "  ✅ Team '#{team.name}' (#{team.team_type})"

# ---------------------------------------------------------------------------
# Roles & Members
# ---------------------------------------------------------------------------
roles_data = [
  {
    role_name: 'Project Lead',
    role_type: 'manager',
    agent_name: 'Todo Team Lead',
    role_description: 'Coordinates the team, reviews all code, makes architectural decisions, and manages task delegation',
    responsibilities: 'Code review, architecture decisions, task delegation, team coordination, worktree management',
    goals: 'Ensure high code quality, consistent architecture, and efficient team collaboration',
    capabilities: %w[code_review task_assignment architecture_decisions conflict_resolution worktree_management],
    constraints: %w[review_all_prs document_decisions],
    tools_allowed: %w[code_diff file_read structured_output git_operations],
    priority_order: 0,
    can_delegate: true,
    can_escalate: true,
    max_concurrent_tasks: 5,
    is_lead: true,
    member_role: 'manager'
  },
  {
    role_name: 'Backend Developer',
    role_type: 'specialist',
    agent_name: 'Todo Backend Developer',
    role_description: 'Builds Rails API models, controllers, services, and migrations',
    responsibilities: 'API development, database design, business logic implementation, migration writing',
    goals: 'Deliver reliable, well-tested API endpoints following Rails conventions',
    capabilities: %w[rails_development migration_writing service_objects api_design],
    constraints: %w[follow_render_patterns inline_indexes frozen_string_literal],
    tools_allowed: %w[code_generation file_write database_operations],
    priority_order: 1,
    can_delegate: false,
    can_escalate: true,
    max_concurrent_tasks: 3,
    is_lead: false,
    member_role: 'executor'
  },
  {
    role_name: 'Frontend Developer',
    role_type: 'specialist',
    agent_name: 'Todo Frontend Developer',
    role_description: 'Builds React TypeScript components, pages, and state management',
    responsibilities: 'UI component development, state management, theme-aware styling, accessibility',
    goals: 'Deliver clean, accessible, theme-compliant React components',
    capabilities: %w[react_development typescript component_design state_management],
    constraints: %w[theme_classes_only no_hardcoded_colors permission_based_access],
    tools_allowed: %w[code_generation file_write],
    priority_order: 2,
    can_delegate: false,
    can_escalate: true,
    max_concurrent_tasks: 3,
    is_lead: false,
    member_role: 'executor'
  },
  {
    role_name: 'QA Engineer',
    role_type: 'specialist',
    agent_name: 'Todo QA Engineer',
    role_description: 'Writes and runs tests for both backend and frontend, reports bugs',
    responsibilities: 'Test writing, edge case validation, bug reporting, regression testing',
    goals: 'Achieve comprehensive test coverage and catch bugs before merge',
    capabilities: %w[rspec_testing jest_testing edge_case_analysis bug_reporting],
    constraints: %w[test_all_endpoints test_error_cases],
    tools_allowed: %w[code_generation file_write test_execution],
    priority_order: 3,
    can_delegate: false,
    can_escalate: true,
    max_concurrent_tasks: 2,
    is_lead: false,
    member_role: 'reviewer'
  },
  {
    role_name: 'DevOps & Documentation',
    role_type: 'worker',
    agent_name: 'Todo DevOps & Docs',
    role_description: 'Manages repository setup, CI/CD, Docker configuration, and project documentation',
    responsibilities: 'Repo management, CI/CD setup, Docker configs, documentation, deployment',
    goals: 'Ensure smooth development workflow with automated testing and clear documentation',
    capabilities: %w[gitea_management ci_cd_configuration docker_setup documentation_writing],
    constraints: %w[no_v_prefix_tags document_all_endpoints],
    tools_allowed: %w[git_operations file_write structured_output],
    priority_order: 4,
    can_delegate: false,
    can_escalate: true,
    max_concurrent_tasks: 2,
    is_lead: false,
    member_role: 'facilitator'
  }
]

roles_created = 0
members_created = 0

roles_data.each do |rd|
  agent = agents[rd[:agent_name]]

  Ai::TeamRole.find_or_create_by!(agent_team: team, role_name: rd[:role_name]) do |r|
    r.account = admin_account
    r.ai_agent = agent
    r.role_type = rd[:role_type]
    r.role_description = rd[:role_description]
    r.responsibilities = rd[:responsibilities]
    r.goals = rd[:goals]
    r.capabilities = rd[:capabilities]
    r.constraints = rd[:constraints]
    r.tools_allowed = rd[:tools_allowed]
    r.priority_order = rd[:priority_order]
    r.can_delegate = rd[:can_delegate]
    r.can_escalate = rd[:can_escalate]
    r.max_concurrent_tasks = rd[:max_concurrent_tasks]
  end
  roles_created += 1

  Ai::AgentTeamMember.find_or_create_by!(
    ai_agent_team_id: team.id,
    ai_agent_id: agent.id
  ) do |m|
    m.role = rd[:member_role]
    m.is_lead = rd[:is_lead]
    m.priority_order = rd[:priority_order]
    m.capabilities = rd[:capabilities]
  end
  members_created += 1
end

# ---------------------------------------------------------------------------
# Channels
# ---------------------------------------------------------------------------
channels_data = [
  {
    name: 'todo-broadcast',
    channel_type: 'broadcast',
    description: 'Team-wide status updates, announcements, and architecture decisions',
    participant_roles: %w[Project\ Lead Backend\ Developer Frontend\ Developer QA\ Engineer DevOps\ &\ Documentation],
    message_schema: {
      'type' => 'object',
      'properties' => {
        'message' => { 'type' => 'string' },
        'priority' => { 'type' => 'string', 'enum' => %w[low normal high urgent] },
        'category' => { 'type' => 'string', 'enum' => %w[announcement decision status blocker] }
      }
    },
    routing_rules: { 'broadcast_to_all' => true }
  },
  {
    name: 'todo-tasks',
    channel_type: 'task',
    description: 'Task assignments, progress updates, and completion tracking',
    participant_roles: %w[Project\ Lead Backend\ Developer Frontend\ Developer QA\ Engineer DevOps\ &\ Documentation],
    message_schema: {
      'type' => 'object',
      'properties' => {
        'task_id' => { 'type' => 'string' },
        'action' => { 'type' => 'string', 'enum' => %w[assign start complete review blocked] },
        'assignee' => { 'type' => 'string' },
        'payload' => { 'type' => 'object' }
      }
    },
    routing_rules: { 'route_by_role' => true, 'priority_routing' => true }
  }
]

channels_created = 0

channels_data.each do |cd|
  Ai::TeamChannel.find_or_create_by!(agent_team: team, name: cd[:name]) do |c|
    c.channel_type = cd[:channel_type]
    c.description = cd[:description]
    c.participant_roles = cd[:participant_roles]
    c.message_schema = cd[:message_schema]
    c.routing_rules = cd[:routing_rules]
    c.is_persistent = true
  end
  channels_created += 1
end

# ---------------------------------------------------------------------------
# Shared Memory Pool
# ---------------------------------------------------------------------------
memory_pool = Ai::MemoryPool.find_or_create_by!(
  account: admin_account,
  name: 'Todo App Team Memory'
) do |mp|
  mp.pool_type = 'team_shared'
  mp.scope = 'persistent'
  mp.version = 1
  mp.team_id = team.id
  mp.persist_across_executions = true
  mp.access_control = {
    'public' => false,
    'agents' => agents.values.map(&:id)
  }
  mp.data = {
    'project' => {
      'name' => 'Todo App',
      'tech_stack' => {
        'backend' => 'Rails 8 API, PostgreSQL, UUIDv7',
        'frontend' => 'React 18, TypeScript, Tailwind CSS',
        'testing' => 'RSpec, Jest, React Testing Library',
        'devops' => 'Gitea, Docker, CI/CD'
      },
      'conventions' => {
        'backend' => [
          'frozen_string_literal pragma on all .rb files',
          'render_success/render_error for all responses',
          'Inline indexes on t.references in migrations',
          'Service objects for complex business logic',
          'Api::V1 namespace for all controllers'
        ],
        'frontend' => [
          'Theme classes only (bg-theme-*, text-theme-*)',
          'Permission-based access control, never roles',
          'No console.log in production',
          'TypeScript strict mode, no any types',
          'Path aliases: @/shared/, @/features/'
        ],
        'git' => [
          'Branch strategy: develop -> feature/* -> release/* -> master',
          'No v prefix on tags',
          'Meaningful commit messages',
          'Feature branches for all changes'
        ]
      }
    },
    'decisions' => [],
    'task_log' => []
  }
  mp.metadata = {
    'created_by' => 'seed',
    'team_name' => 'Todo App Development Team'
  }
  mp.retention_policy = {
    'max_entries' => 1000,
    'ttl_days' => 90
  }
end

puts "  ✅ Memory pool '#{memory_pool.name}' (#{memory_pool.pool_type})"

# ---------------------------------------------------------------------------
# Agent Connections (shared memory links)
# ---------------------------------------------------------------------------
connections_created = 0

agents.each_value do |agent|
  Ai::AgentConnection.find_or_create_by!(
    account: admin_account,
    connection_type: 'shared_memory',
    source_type: 'Ai::Agent',
    source_id: agent.id,
    target_type: 'Ai::MemoryPool',
    target_id: memory_pool.id
  ) do |c|
    c.status = 'active'
    c.strength = 0.8
    c.metadata = { 'access_level' => 'read_write', 'pool_name' => memory_pool.name }
  end
  connections_created += 1
end

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
puts "\n📊 AI Todo App Team Summary:"
puts "   Agents: #{agents_created}"
puts "   Team: #{team.name} (#{team.team_type}, #{team.coordination_strategy})"
puts "   Roles: #{roles_created}"
puts "   Members: #{members_created}"
puts "   Channels: #{channels_created}"
puts "   Memory Pool: #{memory_pool.name}"
puts "   Connections: #{connections_created}"
puts "✅ AI Todo App Team seeding completed!"
