# frozen_string_literal: true

FactoryBot.define do
  factory :invitation do
    association :account
    association :inviter, factory: :user

    sequence(:email) { |n| "invited-user-#{n}@example.com" }
    first_name { Faker::Name.first_name }
    last_name { Faker::Name.last_name }

    # Token will be auto-generated by model, but we need to allow tests to override
    transient do
      raw_token { nil }
    end

    after(:build) do |invitation, evaluator|
      if evaluator.raw_token.present?
        invitation.token = evaluator.raw_token
        invitation.token_digest = Digest::SHA256.hexdigest(evaluator.raw_token)
      elsif invitation.token.blank?
        # Let the model's callback handle it
        invitation.token = nil
        invitation.token_digest = nil
      else
        # Token was set manually, generate digest
        invitation.token_digest = Digest::SHA256.hexdigest(invitation.token) if invitation.token_digest.blank?
      end
    end

    role_names { ['member'] }
    status { 'pending' }
    expires_at { 7.days.from_now }

    trait :expired do
      expires_at { 1.day.ago }
    end

    trait :accepted do
      status { 'accepted' }
      accepted_at { 1.day.ago }
    end

    trait :cancelled do
      status { 'cancelled' }
    end

    trait :with_multiple_roles do
      role_names { ['member', 'billing.viewer'] }
    end

    trait :manager_role do
      role_names { ['account.manager'] }
    end
  end
end
